In [1]:
from pathlib import Path

import pandas as pd

In [2]:
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

CAMINHO_DADOS_BRUTOS = BASE_DIR / "dados_brutos"
ARQUIVO_BRUTO = CAMINHO_DADOS_BRUTOS / "dados_2026-04-14.xlsx"

ARQUIVO_BRUTO

WindowsPath('C:/Users/heron/Downloads/CofiexBI/dados_brutos/dados_2026-04-14.xlsx')

In [3]:
df_raw = pd.read_excel(
    ARQUIVO_BRUTO,
    sheet_name="Dados"
)

df_raw.head()

,cd_pleito,nu_processo_sei,nm_pleito,sg_pleito,nm_proponente,de_tipo_operacao,de_fase,de_fonte,sg_fonte,nm_moeda,...,sg_uf,dt_ultimo_recebimento,dt_primeira_cofiex,dt_validade_recomendacao,dt_reuniao_negociacao,dt_publicacao_dou,dt_assinatura,dt_ultimo_desembolso_original,dt_ultimo_desembolso_vigente,nu_operacao
0,97,NaN,Projeto de Reestruturação Organizacional,PRO,Eletrobras Furnas,Doações,Finalizada,Banco Interamericano de Desenvolvimento - BID/...,BID/ICSF,Dólar,...,RJ,2011-10-28,NaN,NaN,NaN,NaN,2012-08-06,2013-07-04,2013-07-04,ATN/FI-13220-BR
1,114,03400.000090/2013-47,Programa de Fortalecimento das Redes de Inclus...,PROREDES,Estado de Sergipe,Operação de crédito externo,Arquivado,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,SE,2024-09-16,2012-10-05,2015-10-17,2014-06-05,2012-10-17,NaN,NaN,NaN,3246/OC-BR
2,116,03400.001343/2012-19,Programa Integrado de Investimentos para Revit...,Canoas para Todos,Município de Canoas - RS,Operação de crédito externo,Repagamento,Corporação Andina de Fomento - CAF,CAF,Dólar,...,RS,2012-09-13,2012-12-14,2015-01-04,2014-01-22,2013-01-04,2014-06-24,2017-06-24,2017-06-24,CFX2183
3,120,NaN,Programa de Consolidação do Equilíbrio Fiscal ...,PROCONFIS/RS II,Estado do Rio Grande do Sul,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,RS,2012-09-14,2013-10-04,2014-10-17,2013-11-13,2012-10-17,2014-05-29,2016-05-29,2016-05-29,3138
4,120,NaN,Programa de Consolidação do Equilíbrio Fiscal ...,PROCONFIS/RS II,Estado do Rio Grande do Sul,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,Dólar,...,RS,2012-09-14,2013-10-04,2014-10-17,2014-04-16,2012-10-17,2014-08-20,2015-12-31,2015-12-31,8379

In [4]:
print(f"Linhas: {df_raw.shape[0]}")
print(f"Colunas: {df_raw.shape[1]}")

df_raw.info()

Linhas: 3548
Colunas: 25
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3548 entries, 0 to 3547
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   cd_pleito                      3548 non-null   object
 1   nu_processo_sei                1094 non-null   object
 2   nm_pleito                      3547 non-null   object
 3   sg_pleito                      3155 non-null   object
 4   nm_proponente                  3548 non-null   object
 5   de_tipo_operacao               3548 non-null   object
 6   de_fase                        3548 non-null   object
 7   de_fonte                       3265 non-null   object
 8   sg_fonte                       3264 non-null   object
 9   nm_moeda                       3265 non-null   object
 10  vl_financiamento_dolar         3265 non-null   float64
 11  vl_contrapartida_dolar         2489 non-null   float64
 12  de_esfera                      3259 non-null   object
 13  nm_regiao                      3548 non-null   object
 14  nm_uf                          3522 non-null   object
 15  sg_uf                          3522 non-null   object
 16  dt_ultimo_recebimento          3142 non-null   object
 17  dt_primeira_cofiex             1918 non-null   object
 18  dt_validade_recomendacao       994 non-null    object
 19  dt_reuniao_negociacao          918 non-null    object
 20  dt_publicacao_dou              1092 non-null   object
 21  dt_assinatura                  1416 non-null   object
 22  dt_ultimo_desembolso_original  1238 non-null   object
 23  dt_ultimo_desembolso_vigente   1412 non-null   object
 24  nu_operacao                    1403 non-null   object
dtypes: float64(2), object(23)
memory usage: 693.1+ KB

In [5]:
df_dicionario = pd.read_excel(
    ARQUIVO_BRUTO,
    sheet_name="Dicionário"
)

df_dicionario.head()

          VARIÁVEL                  DESCRIÇÃO
0        cd_pleito           Número do Pleito
1  nu_processo_sei     Número do Processo SEI
2        nm_pleito   Nome do Programa/Projeto
3        sg_pleito  Sigla do Programa/Projeto
4    nm_proponente         Nome do Proponente

In [6]:
print(f"Linhas: {df_dicionario.shape[0]}")
print(f"Colunas: {df_dicionario.shape[1]}")

df_dicionario

Linhas: 25
Colunas: 2

,VARIÁVEL,DESCRIÇÃO
0,cd_pleito,Número do Pleito
1,nu_processo_sei,Número do Processo SEI
2,nm_pleito,Nome do Programa/Projeto
3,sg_pleito,Sigla do Programa/Projeto
4,nm_proponente,Nome do Proponente
5,de_tipo_operacao,Modalidade da Operação
6,de_fase,Fase do Programa/Projeto no Momento da Extraçã...
7,de_fonte,Fonte de Financiamento (Instituição Financeira)
8,sg_fonte,Silga da Fonte de Financiamento (Instituição F...
9,nm_moeda,Moeda de Financiamento Presente no Contrato
10,vl_financiamento_dolar,Valor do Financiamento em Dólares Americanos
11,vl_contrapartida_dolar,Valor da Contrapartida Financeira em Dólares A...
12,de_esfera,Esfera do Programa/Projeto (Municipal; Estadua...
13,nm_regiao,Região Geográfica do Proponente
14,nm_uf,Unidade Federativa do Proponente
15,sg_uf,Sigla da Unidade Federativa do Proponente
16,dt_ultimo_recebimento,Data de Recebimento da Última Versão do Pleito
17,dt_primeira_cofiex,Data da Reunião da Cofiex de Aprovação da Prep...
18,dt_validade_recomendacao,Data de Validade da Resolução Cofiex que Aprov...
19,dt_reuniao_negociacao,Data da Reunião de Negociação do Contrato
20,dt_publicacao_dou,Data de Publicação no DOU
21,dt_assinatura,Data de Assinatura do Contrato de Empréstimo a...
22,dt_ultimo_desembolso_original,Data/Previsão da Ocorrência do Último Desembol...
23,dt_ultimo_desembolso_vigente,Data/Previsão da Ocorrência Vigente do Último ...
24,nu_operacao,Número da Operação ou Número do Contrato

In [7]:
fonte_dados = {
    "arquivo_bruto": str(ARQUIVO_BRUTO),
    "abas_utilizadas": ["Dados", "Dicionário"],
    "data_extracao": "2026-04-14",
    "data_acesso": "2026-05-23",
    "observacao": "A data de extração foi inferida a partir do nome do arquivo bruto."
}

fonte_dados

{'arquivo_bruto': 'C:\\Users\\heron\\Downloads\\CofiexBI\\dados_brutos\\dados_2026-04-14.xlsx',
 'abas_utilizadas': ['Dados', 'Dicionário'],
 'data_extracao': '2026-04-14',
 'data_acesso': '2026-05-23',
 'observacao': 'A data de extração foi inferida a partir do nome do arquivo bruto.'}

In [8]:
df_tratado = df_raw.copy()

In [9]:
print(f"df_raw: {df_raw.shape[0]} linhas e {df_raw.shape[1]} colunas")
print(f"df_tratado: {df_tratado.shape[0]} linhas e {df_tratado.shape[1]} colunas")

df_raw: 3548 linhas e 25 colunas
df_tratado: 3548 linhas e 25 colunas

In [10]:
# Conferência de preservação da estrutura inicial
assert df_raw.shape == df_tratado.shape

print("df_raw preservado como base original.")
print("df_tratado criado como cópia para tratamento.")

df_raw preservado como base original.
df_tratado criado como cópia para tratamento.

In [11]:
print("Dimensão da base:")
print(f"{df_raw.shape[0]} linhas e {df_raw.shape[1]} colunas")

print("\nInformações da base:")
df_raw.info()

display(df_raw.head())

Dimensão da base:
3548 linhas e 25 colunas

Informações da base:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3548 entries, 0 to 3547
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   cd_pleito                      3548 non-null   object
 1   nu_processo_sei                1094 non-null   object
 2   nm_pleito                      3547 non-null   object
 3   sg_pleito                      3155 non-null   object
 4   nm_proponente                  3548 non-null   object
 5   de_tipo_operacao               3548 non-null   object
 6   de_fase                        3548 non-null   object
 7   de_fonte                       3265 non-null   object
 8   sg_fonte                       3264 non-null   object
 9   nm_moeda                       3265 non-null   object
 10  vl_financiamento_dolar         3265 non-null   float64
 11  vl_contrapartida_dolar         2489 non-null   float64
 12  de_esfera                      3259 non-null   object
 13  nm_regiao                      3548 non-null   object
 14  nm_uf                          3522 non-null   object
 15  sg_uf                          3522 non-null   object
 16  dt_ultimo_recebimento          3142 non-null   object
 17  dt_primeira_cofiex             1918 non-null   object
 18  dt_validade_recomendacao       994 non-null    object
 19  dt_reuniao_negociacao          918 non-null    object
 20  dt_publicacao_dou              1092 non-null   object
 21  dt_assinatura                  1416 non-null   object
 22  dt_ultimo_desembolso_original  1238 non-null   object
 23  dt_ultimo_desembolso_vigente   1412 non-null   object
 24  nu_operacao                    1403 non-null   object
dtypes: float64(2), object(23)
memory usage: 693.1+ KB

,cd_pleito,nu_processo_sei,nm_pleito,sg_pleito,nm_proponente,de_tipo_operacao,de_fase,de_fonte,sg_fonte,nm_moeda,...,sg_uf,dt_ultimo_recebimento,dt_primeira_cofiex,dt_validade_recomendacao,dt_reuniao_negociacao,dt_publicacao_dou,dt_assinatura,dt_ultimo_desembolso_original,dt_ultimo_desembolso_vigente,nu_operacao
0,97,NaN,Projeto de Reestruturação Organizacional,PRO,Eletrobras Furnas,Doações,Finalizada,Banco Interamericano de Desenvolvimento - BID/...,BID/ICSF,Dólar,...,RJ,2011-10-28,NaN,NaN,NaN,NaN,2012-08-06,2013-07-04,2013-07-04,ATN/FI-13220-BR
1,114,03400.000090/2013-47,Programa de Fortalecimento das Redes de Inclus...,PROREDES,Estado de Sergipe,Operação de crédito externo,Arquivado,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,SE,2024-09-16,2012-10-05,2015-10-17,2014-06-05,2012-10-17,NaN,NaN,NaN,3246/OC-BR
2,116,03400.001343/2012-19,Programa Integrado de Investimentos para Revit...,Canoas para Todos,Município de Canoas - RS,Operação de crédito externo,Repagamento,Corporação Andina de Fomento - CAF,CAF,Dólar,...,RS,2012-09-13,2012-12-14,2015-01-04,2014-01-22,2013-01-04,2014-06-24,2017-06-24,2017-06-24,CFX2183
3,120,NaN,Programa de Consolidação do Equilíbrio Fiscal ...,PROCONFIS/RS II,Estado do Rio Grande do Sul,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,RS,2012-09-14,2013-10-04,2014-10-17,2013-11-13,2012-10-17,2014-05-29,2016-05-29,2016-05-29,3138
4,120,NaN,Programa de Consolidação do Equilíbrio Fiscal ...,PROCONFIS/RS II,Estado do Rio Grande do Sul,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,Dólar,...,RS,2012-09-14,2013-10-04,2014-10-17,2014-04-16,2012-10-17,2014-08-20,2015-12-31,2015-12-31,8379

In [12]:
relatorio_nulos = (
    df_raw
    .isna()
    .sum()
    .reset_index()
    .rename(columns={
        "index": "coluna",
        0: "qtd_nulos"
    })
)

relatorio_nulos["percentual_nulos"] = (
    relatorio_nulos["qtd_nulos"] / len(df_raw) * 100
).round(2)

relatorio_nulos = relatorio_nulos.sort_values(
    by="qtd_nulos",
    ascending=False
)

relatorio_nulos

                           coluna  qtd_nulos  percentual_nulos
19          dt_reuniao_negociacao       2630             74.13
18       dt_validade_recomendacao       2554             71.98
20              dt_publicacao_dou       2456             69.22
1                 nu_processo_sei       2454             69.17
22  dt_ultimo_desembolso_original       2310             65.11
24                    nu_operacao       2145             60.46
23   dt_ultimo_desembolso_vigente       2136             60.20
21                  dt_assinatura       2132             60.09
17             dt_primeira_cofiex       1630             45.94
11         vl_contrapartida_dolar       1059             29.85
16          dt_ultimo_recebimento        406             11.44
3                       sg_pleito        393             11.08
12                      de_esfera        289              8.15
8                        sg_fonte        284              8.00
10         vl_financiamento_dolar        283              7.98
9                        nm_moeda        283              7.98
7                        de_fonte        283              7.98
14                          nm_uf         26              0.73
15                          sg_uf         26              0.73
2                       nm_pleito          1              0.03
13                      nm_regiao          0              0.00
6                         de_fase          0              0.00
5                de_tipo_operacao          0              0.00
4                   nm_proponente          0              0.00
0                       cd_pleito          0              0.00

In [13]:
valores_unicos_por_coluna = (
    df_raw
    .nunique(dropna=False)
    .reset_index()
    .rename(columns={
        "index": "coluna",
        0: "qtd_valores_unicos"
    })
    .sort_values(by="qtd_valores_unicos", ascending=False)
)

valores_unicos_por_coluna

                           coluna  qtd_valores_unicos
0                       cd_pleito                3364
2                       nm_pleito                3248
3                       sg_pleito                2925
16          dt_ultimo_recebimento                1717
10         vl_financiamento_dolar                1515
24                    nu_operacao                1338
11         vl_contrapartida_dolar                1262
21                  dt_assinatura                1106
1                 nu_processo_sei                1027
23   dt_ultimo_desembolso_vigente                 895
19          dt_reuniao_negociacao                 830
22  dt_ultimo_desembolso_original                 804
4                   nm_proponente                 488
17             dt_primeira_cofiex                 394
18       dt_validade_recomendacao                 290
20              dt_publicacao_dou                 219
7                        de_fonte                 115
8                        sg_fonte                 112
15                          sg_uf                  28
14                          nm_uf                  28
6                         de_fase                   8
5                de_tipo_operacao                   7
9                        nm_moeda                   7
13                      nm_regiao                   6
12                      de_esfera                   4

In [14]:
qtd_duplicatas_exatas = df_raw.duplicated().sum()

qtd_duplicatas_exatas

np.int64(0)

In [15]:
qtd_cd_pleito_repetidos = df_raw["cd_pleito"].duplicated(keep=False).sum()

qtd_cd_pleito_repetidos

np.int64(342)

In [16]:
contagem_cd_pleito = df_raw["cd_pleito"].value_counts()

qtd_codigos_cd_pleito_repetidos = (contagem_cd_pleito > 1).sum()

qtd_codigos_cd_pleito_repetidos

np.int64(158)

In [17]:
print(f"Linhas com cd_pleito repetido: {qtd_cd_pleito_repetidos}")
print(f"Códigos cd_pleito que aparecem mais de uma vez: {qtd_codigos_cd_pleito_repetidos}")

Linhas com cd_pleito repetido: 342
Códigos cd_pleito que aparecem mais de uma vez: 158

In [18]:
df_cd_pleito_repetidos = (
    df_raw[df_raw["cd_pleito"].duplicated(keep=False)]
    .sort_values(by="cd_pleito")
)

df_cd_pleito_repetidos.head(20)

,cd_pleito,nu_processo_sei,nm_pleito,sg_pleito,nm_proponente,de_tipo_operacao,de_fase,de_fonte,sg_fonte,nm_moeda,...,sg_uf,dt_ultimo_recebimento,dt_primeira_cofiex,dt_validade_recomendacao,dt_reuniao_negociacao,dt_publicacao_dou,dt_assinatura,dt_ultimo_desembolso_original,dt_ultimo_desembolso_vigente,nu_operacao
3,120,NaN,Programa de Consolidação do Equilíbrio Fiscal ...,PROCONFIS/RS II,Estado do Rio Grande do Sul,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,RS,2012-09-14,2013-10-04,2014-10-17,2013-11-13,2012-10-17,2014-05-29,2016-05-29,2016-05-29,3138
4,120,NaN,Programa de Consolidação do Equilíbrio Fiscal ...,PROCONFIS/RS II,Estado do Rio Grande do Sul,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,Dólar,...,RS,2012-09-14,2013-10-04,2014-10-17,2014-04-16,2012-10-17,2014-08-20,2015-12-31,2015-12-31,8379
3445,176200631/2025,03101.000240/2025-21,PROGRAMA DE DESENVOLVIMENTO URBANO NO MUNICÍPI...,"PETROLINA, CRESCER MAIS",Município de Petrolina,Operação de crédito externo,Aprovado,Fundo da Organização dos Países Exportadores d...,Fundo OPEP,Dólar,...,PE,2025-02-25,2025-03-27,2027-04-23,NaN,NaN,NaN,NaN,NaN,NaN
3444,176200631/2025,03101.000240/2025-21,PROGRAMA DE DESENVOLVIMENTO URBANO NO MUNICÍPI...,"PETROLINA, CRESCER MAIS",Município de Petrolina,Operação de crédito externo,Aprovado,Fundo Financeiro para o Desenvolvimento da Bac...,FONPLATA,Dólar,...,PE,2025-02-25,2025-03-27,2027-04-23,NaN,NaN,NaN,NaN,NaN,NaN
3448,1943105475/2025,03101.001942/2025-21,Parque Tecnológico de Brasília – BIOTIC: Infra...,BIOTIC-Inova,BIOTIC S.A.,Operação de crédito externo,Aprovado,Fundo da Organização dos Países Exportadores d...,Fundo OPEP,Dólar,...,DF,2025-08-08,2025-09-18,2027-09-25,NaN,NaN,NaN,NaN,NaN,NaN
3447,1943105475/2025,03101.001942/2025-21,Parque Tecnológico de Brasília – BIOTIC: Infra...,BIOTIC-Inova,BIOTIC S.A.,Operação de crédito externo,Aprovado,Fundo Financeiro para o Desenvolvimento da Bac...,FONPLATA,Dólar,...,DF,2025-08-08,2025-09-18,2027-09-25,NaN,NaN,NaN,NaN,NaN,NaN
3465,3511351018/2025,03101.000222/2025-49,Programa BNDES-BIRD de Apoio ao Arco da Restau...,Programa BNDES-BIRD de Apoio ao Arco da Restau...,Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Aprovado,Banco Internacional para Reconstrução e Desenv...,BIRD/CIF,Dólar,...,NaN,2025-02-25,2025-03-27,2027-04-23,NaN,NaN,NaN,NaN,NaN,NaN
3464,3511351018/2025,03101.000222/2025-49,Programa BNDES-BIRD de Apoio ao Arco da Restau...,Programa BNDES-BIRD de Apoio ao Arco da Restau...,Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Aprovado,Banco Internacional para Reconstrução e Desenv...,BIRD,Dólar,...,NaN,2025-02-25,2025-03-27,2027-04-23,NaN,NaN,NaN,NaN,NaN,NaN
3470,4106356693/2025,03101.002858/2025-25,Programa de Financiamento da Modernização da I...,Brasil Mais TV 3.0,Ministério das Comunicações,Operação de crédito externo,Aprovado,Banco Internacional para Reconstrução e Desenv...,BIRD,Dólar,...,NaN,2025-11-04,2025-12-11,2027-12-22,NaN,NaN,NaN,NaN,NaN,NaN
3469,4106356693/2025,03101.002858/2025-25,Programa de Financiamento da Modernização da I...,Brasil Mais TV 3.0,Ministério das Comunicações,Operação de crédito externo,Aprovado,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,NaN,2025-11-04,2025-12-11,2027-12-22,NaN,NaN,NaN,NaN,NaN,NaN
3480,5384019907/2025,03101.001014/2025-67,PROGRAMA JOINVILLE RESILIENTE E SUSTENTÁVEL: I...,JOINVILLE RESILIENTE E SUSTENTÁVEL,Município de Joinville,Operação de crédito externo,Aprovado,Fundo da Organização dos Países Exportadores d...,Fundo OPEP,Dólar,...,SC,2025-07-10,2025-09-18,2027-09-25,NaN,NaN,NaN,NaN,NaN,NaN
3479,5384019907/2025,03101.001014/2025-67,PROGRAMA JOINVILLE RESILIENTE E SUSTENTÁVEL: I...,JOINVILLE RESILIENTE E SUSTENTÁVEL,Município de Joinville,Operação de crédito externo,Aprovado,Fundo Financeiro para o Desenvolvimento da Bac...,FONPLATA,Dólar,...,SC,2025-07-10,2025-09-18,2027-09-25,NaN,NaN,NaN,NaN,NaN,NaN
3482,5492643979/2024,03101.000219/2025-25,Melhoria da Sustentabilidade da Dívida do Esta...,MSDESP,Estado de São Paulo,Operação de crédito externo,Aprovado,Banco Internacional para Reconstrução e Desenv...,BIRD/MIGA,Dólar,...,SP,2025-02-21,2025-03-27,2027-04-23,NaN,NaN,NaN,NaN,NaN,NaN
3481,5492643979/2024,03101.000219/2025-25,Melhoria da Sustentabilidade da Dívida do Esta...,MSDESP,Estado de São Paulo,Operação de crédito externo,Aprovado,Banco Internacional para Reconstrução e Desenv...,BIRD,Dólar,...,SP,2025-02-21,2025-03-27,2027-04-23,NaN,NaN,NaN,NaN,NaN,NaN
39,57754,NaN,Saneamento Básico de Fortaleza - SANEFOR,SANEFOR,Estado do Ceará,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID/...,BID,Dólar,...,CE,1992-02-07,1991-06-05,NaN,1992-08-21,NaN,1992-12-09,1996-12-09,1998-09-09,0892-FOE
38,57754,NaN,Saneamento Básico de Fortaleza - SANEFOR,SANEFOR,Estado do Ceará,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,CE,1992-02-07,1991-06-05,NaN,1992-08-21,NaN,1992-12-09,1996-12-09,1998-09-09,0695-CO
60,57775,NaN,Programa Gerenciamento Malha Rodoviária de Toc...,RODOVIAS TO,Estado do Tocantins,Operação de crédito externo,Finalizada,Banco Internacional para Reconstrução e Desenv...,BIRD,Dólar,...,TO,1991-06-26,1995-09-18,NaN,1993-11-05,NaN,1994-06-24,1999-12-31,1999-12-31,3714-0
61,57775,NaN,Programa Gerenciamento Malha Rodoviária de Toc...,RODOVIAS TO,Estado do Tocantins,Operação de crédito externo,Repagamento,Banco do Japão para Cooperação Internacional -...,JBIC,Dólar,...,TO,1991-06-26,1995-09-18,NaN,NaN,NaN,1997-03-17,NaN,1999-12-31,NaN
64,57777,NaN,Reabilitação e Descentralização de Rodovias Fe...,DESC. RODOVIAS I,República Federativa do Brasil,Operação de crédito externo,Finalizada,Banco Internacional para Reconstrução e Desenv...,BIRD,Dólar,...,DF,1991-06-25,1991-07-11,NaN,1997-05-09,NaN,1997-12-10,2002-12-31,2005-12-17,4188-0
63,57777,NaN,Reabilitação e Descentralização de Rodovias Fe...,DESC. RODOVIAS I,República Federativa do Brasil,Operação de crédito externo,Finalizada,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,DF,1991-06-25,1991-07-11,NaN,1997-08-29,NaN,1998-03-15,2002-03-15,2007-03-15,1046/CO-BR

In [19]:
qtd_nu_operacao_repetidos = (
    df_raw["nu_operacao"]
    .dropna()
    .duplicated(keep=False)
    .sum()
)

qtd_nu_operacao_repetidos

np.int64(82)

In [20]:
contagem_nu_operacao = df_raw["nu_operacao"].dropna().value_counts()

qtd_codigos_nu_operacao_repetidos = (
    contagem_nu_operacao > 1
).sum()

qtd_codigos_nu_operacao_repetidos

np.int64(16)

In [21]:
print(f"Linhas com nu_operacao repetido: {qtd_nu_operacao_repetidos}")
print(f"Números de operação que aparecem mais de uma vez: {qtd_codigos_nu_operacao_repetidos}")

Linhas com nu_operacao repetido: 82
Números de operação que aparecem mais de uma vez: 16

In [22]:
df_nu_operacao_repetidos = (
    df_raw[
        df_raw["nu_operacao"].notna()
        & df_raw["nu_operacao"].duplicated(keep=False)
    ]
    .sort_values(by="nu_operacao")
)

df_nu_operacao_repetidos.head(20)

,cd_pleito,nu_processo_sei,nm_pleito,sg_pleito,nm_proponente,de_tipo_operacao,de_fase,de_fonte,sg_fonte,nm_moeda,...,sg_uf,dt_ultimo_recebimento,dt_primeira_cofiex,dt_validade_recomendacao,dt_reuniao_negociacao,dt_publicacao_dou,dt_assinatura,dt_ultimo_desembolso_original,dt_ultimo_desembolso_vigente,nu_operacao
1358,59050,NaN,"DOAÇÃO ""CAPIBARIBE MELHOR"" / Município de Reci...",DOAÇÃO CAPIBARIBE MELHOR,Município de Recife - PE,Doações,Finalizada,Banco Internacional para Reconstrução e Desenv...,WB-JG,Dólar,...,PE,2003-12-01,2003-12-23,NaN,NaN,NaN,2004-01-01,2004-01-01,2004-01-01,0
1195,58874,NaN,Projeto de Suporte ao Desenv. de Empreend. de ...,EMPREEND.AGRs. FAMILIARES,República Federativa do Brasil,Operação de crédito externo,Arquivado,Fundo Internacional para o Desenvolvimento da...,FIDA,SDR,...,DF,2001-06-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1882,59575,NaN,Doação para Estudos Educacionais do Ministério...,DOAÇÃO ESTUDOS MEC,República Federativa do Brasil,Doações,Finalizada,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,DF,2008-06-10,NaN,NaN,NaN,NaN,2009-01-01,2009-01-01,2009-01-01,0
2091,59782,03400.001323/2010-86,Quinta Fase Operacional do Programa de Pequena...,Small Grants - GEF 5,"Instituto Sociedade, População e Natureza - ISPN",Contribuição Financeira não Reembolsável GEF,Finalizada,GEF/Programa de Desenvolvimento das Nações Uni...,GEF/PNUD,Dólar,...,DF,2010-08-18,NaN,NaN,NaN,NaN,2013-01-01,2017-02-28,2017-02-28,0
2258,59964,03400.000758/2013-56,Saneamento urbano da cidade de Aceguá-RS. Obra...,Saneamento Urbano Integrado Aceguá-RS,Estado do Rio Grande do Sul,Doações,Finalizada,Fundo para Convergência Estrutural e Fortaleci...,FOCEM,Dólar,...,RS,2013-07-01,NaN,2015-09-09,NaN,2013-09-09,2013-11-06,2014-05-06,NaN,0
2766,60578,03400.000647/2018-54,Conservação da Saúde e Integridade dos Ecossis...,GEF Mar II,Ministério do Meio Ambiente - MMA,Doações,Em execução,Fundo Global para o Meio Ambiente - GEF,GEF,Dólar,...,DF,2019-04-23,NaN,NaN,NaN,NaN,2021-05-28,2026-05-28,NaN,0
959,58635,NaN,Programa de Desenvolvimento do Turismo no Nord...,PRODETUR NE II - 2ª Fase,Banco do Nordeste do Brasil - BNB,Operação de crédito externo,Arquivado,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,DF,2000-05-21,2001-12-18,NaN,NaN,NaN,NaN,NaN,NaN,0
2979,60789,12120.100332/2021-49,PROGRAMA DE INFRAESTRUTURA URBANA E DESENVOLVI...,PROINPS/BA,Município de Porto Seguro,Operação de crédito externo,Negociação concluída,Corporação Andina de Fomento - CAF,CAF,Dólar,...,BA,2021-08-03,2021-10-25,NaN,2022-11-04,2021-11-08,NaN,NaN,NaN,0
2921,60733,12120.100337/2020-91,Contribuição Financeira não Reembolsável de Aj...,AÇÕES DE COMBATE AO COVID-19 - SALVADOR/BA,Município de Salvador - BA,Doações,Finalizada,Corporação Andina de Fomento - CAF,CAF,Dólar,...,BA,2020-05-25,2020-05-29,NaN,NaN,2020-06-05,2020-06-12,2021-06-12,2021-06-12,00
1104,58782,NaN,Doação - Projeto de Apoio à Expansão e Sustent...,DOAÇÃO SAÚDE FAMÍLIA,República Federativa do Brasil,Doações,Finalizada,Banco Internacional para Reconstrução e Desenv...,WB-JG,Dólar,...,DF,2001-02-12,2001-03-12,NaN,NaN,NaN,2001-03-13,2002-06-30,2002-10-31,00
1134,58813,NaN,Estudo de Viab. I. Para à Recup. de Imóveis Ha...,DOAÇÃO CENTROS HIST.,Caixa Econômica Federal - CEF,Doações,Finalizada,Banco Interamericano de Desenvolvimento - BID/...,BID/FUMIN,Real,...,DF,2001-04-16,2001-05-31,NaN,NaN,NaN,2001-03-06,2002-09-06,2003-12-12,00
1141,58820,NaN,Doação - Programa de Sistemas de Transportes U...,DOAÇÃO TRANSPORTE PR,Estado do Paraná,Doações,Finalizada,Banco Interamericano de Desenvolvimento - BID/JSF,BID/JSF,Dólar,...,PR,2001-05-22,2001-07-06,NaN,NaN,NaN,2002-04-01,2004-04-01,2004-04-01,00
1257,58951,NaN,Programa de Fortalecimento do Controle do Espa...,CL-X e P-3BR,República Federativa do Brasil,Operação Comercial,Repagamento,Banco Bilbao Vizcaya Argentaria S.A,BBVA,Dólar,...,DF,2001-06-08,2005-02-03,2006-11-10,NaN,2004-11-10,2005-03-10,2012-12-31,2014-12-31,00
1335,59028,NaN,Integrated and Sustainable Management of Trans...,GEF-AMAZONAS,Agência Nacional de Águas - ANA,Contribuição Financeira não Reembolsável GEF,Finalizada,GEF/Programa Nações Unidas Para o Meio Ambient...,GEF/PNUMA,Dólar,...,DF,2007-09-14,NaN,NaN,NaN,NaN,2010-09-07,2014-09-30,2014-09-30,00
1484,59177,NaN,Promoção de Empresas Exportadoras e de Infra-E...,EXPORT PROMOTION,Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Arquivado,Banco do Japão para Cooperação Internacional -...,JBIC,Dólar,...,RJ,2005-04-26,2005-05-25,NaN,NaN,NaN,NaN,NaN,NaN,00
1564,59257,NaN,Programa KfW para Pequenas Centrais Hidrelétr...,PROGRAMA KFW - PCH,Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Repagamento,KfW Entwicklungsbank,KfW,Euro,...,RJ,2006-07-13,2006-12-07,NaN,2009-08-24,2006-12-28,2010-12-10,2011-11-30,2011-11-30,00
1676,59369,NaN,Doação - Projeto Piloto de Produção de Biodiesel,Doação Biodiesel - BA,Estado da Bahia,Doações,Finalizada,Fundo Internacional para o Desenvolvimento da...,FIDA,SDR,...,BA,2006-05-04,2006-07-19,NaN,NaN,2006-08-07,2008-07-31,2013-03-31,2013-03-31,00
2809,60619,12120.100467/2019-90,Programa de Modernização do DNIT- DNIT 3.0,Programa DNIT 3.0,Ministério da Infraestrutura - MInfra,Operação de crédito externo,Arquivado,Banco Internacional para Reconstrução e Desenv...,BIRD,Dólar,...,DF,2019-07-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00
1852,59543,NaN,JBIC/Infra-Estrutura,BNDES/JBIC-INFRA,Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Repagamento,Banco do Japão para Cooperação Internacional -...,JBIC,Dólar,...,RJ,2008-02-29,2008-09-26,NaN,NaN,2008-10-13,2009-01-01,2013-01-01,2013-01-01,00
1898,59592,NaN,Apoio na Implementação do Plano de Monitoramen...,GRULAC,Ministério do Meio Ambiente - MMA,Contribuição Financeira não Reembolsável GEF,Finalizada,Fundo Global para o Meio Ambiente - GEF,GEF,Dólar,...,DF,2008-07-18,NaN,NaN,NaN,NaN,2009-07-20,2012-03-31,2012-03-31,00

In [23]:
categorias_tipo_operacao = (
    df_raw["de_tipo_operacao"]
    .value_counts(dropna=False)
    .rename_axis("categoria")
    .reset_index(name="qtd_registros")
)

categorias_tipo_operacao

                                      categoria  qtd_registros
0                   Operação de crédito externo           2643
1                                       Doações            532
2  Contribuição Financeira não Reembolsável GEF            273
3                                        Outros             64
4      Contribuição financeira não reembolsável             15
5                            Operação Comercial             12
6                        Cooperação Técnica GEF              9

In [24]:
categorias_tipo_operacao["percentual"] = (
    categorias_tipo_operacao["qtd_registros"] / len(df_raw) * 100
).round(2)

categorias_tipo_operacao

                                      categoria  qtd_registros  percentual
0                   Operação de crédito externo           2643       74.49
1                                       Doações            532       14.99
2  Contribuição Financeira não Reembolsável GEF            273        7.69
3                                        Outros             64        1.80
4      Contribuição financeira não reembolsável             15        0.42
5                            Operação Comercial             12        0.34
6                        Cooperação Técnica GEF              9        0.25

In [25]:
categorias_fase = (
    df_raw["de_fase"]
    .value_counts(dropna=False)
    .rename_axis("categoria")
    .reset_index(name="qtd_registros")
)

categorias_fase["percentual"] = (
    categorias_fase["qtd_registros"] / len(df_raw) * 100
).round(2)

categorias_fase

              categoria  qtd_registros  percentual
0             Arquivado           1587       44.73
1           Repagamento            706       19.90
2            Finalizada            598       16.85
3              Aprovado            197        5.55
4             Reprovada            190        5.36
5           Em execução            168        4.74
6  Negociação concluída             95        2.68
7         Em negociação              7        0.20

In [26]:
categorias_sg_fonte = (
    df_raw["sg_fonte"]
    .value_counts(dropna=False)
    .rename_axis("categoria")
    .reset_index(name="qtd_registros")
)

categorias_sg_fonte["percentual"] = (
    categorias_sg_fonte["qtd_registros"] / len(df_raw) * 100
).round(2)

categorias_sg_fonte

               categoria  qtd_registros  percentual
0                    BID            898       25.31
1                   BIRD            812       22.89
2                    NaN            284        8.00
3                    CAF            237        6.68
4                    GEF            161        4.54
..                   ...            ...         ...
107                CESVI              1        0.03
108             BID/FCAS              1        0.03
109  Consórcio de Bancos              1        0.03
110              BID/IID              1        0.03
111            BIRD/MIGA              1        0.03

[112 rows x 3 columns]

In [27]:
print(f"Quantidade de categorias em sg_fonte: {df_raw['sg_fonte'].nunique(dropna=False)}")

Quantidade de categorias em sg_fonte: 112

In [28]:
categorias_nm_regiao = (
    df_raw["nm_regiao"]
    .value_counts(dropna=False)
    .rename_axis("categoria")
    .reset_index(name="qtd_registros")
)

categorias_nm_regiao["percentual"] = (
    categorias_nm_regiao["qtd_registros"] / len(df_raw) * 100
).round(2)

categorias_nm_regiao

      categoria  qtd_registros  percentual
0      Nacional           1087       30.64
1       Sudeste            844       23.79
2      Nordeste            618       17.42
3           Sul            472       13.30
4         Norte            270        7.61
5  Centro-Oeste            257        7.24

In [29]:
categorias_sg_uf = (
    df_raw["sg_uf"]
    .value_counts(dropna=False)
    .rename_axis("categoria")
    .reset_index(name="qtd_registros")
)

categorias_sg_uf["percentual"] = (
    categorias_sg_uf["qtd_registros"] / len(df_raw) * 100
).round(2)

categorias_sg_uf

   categoria  qtd_registros  percentual
0         DF           1134       31.96
1         SP            369       10.40
2         RJ            230        6.48
3         RS            211        5.95
4         MG            176        4.96
5         CE            160        4.51
6         SC            143        4.03
7         BA            120        3.38
8         PR            118        3.33
9         PE             96        2.71
10        PA             81        2.28
11        AM             76        2.14
12        ES             69        1.94
13        GO             63        1.78
14        PI             61        1.72
15        MS             59        1.66
16        MA             51        1.44
17        TO             50        1.41
18        PB             45        1.27
19        SE             40        1.13
20        MT             33        0.93
21        RN             33        0.93
22        AL             30        0.85
23       NaN             26        0.73
24        AC             26        0.73
25        RO             22        0.62
26        AP             18        0.51
27        RR              8        0.23

In [30]:
print(f"Quantidade de categorias em nm_regiao: {df_raw['nm_regiao'].nunique(dropna=False)}")
print(f"Quantidade de categorias em sg_uf: {df_raw['sg_uf'].nunique(dropna=False)}")

Quantidade de categorias em nm_regiao: 6
Quantidade de categorias em sg_uf: 28

In [31]:
diagnostico_tipos = pd.DataFrame({
    "coluna": df_raw.columns,
    "tipo_inferido": df_raw.dtypes.astype(str).values,
    "qtd_nulos": df_raw.isna().sum().values,
    "qtd_valores_unicos": df_raw.nunique(dropna=False).values
})

diagnostico_tipos

                           coluna tipo_inferido  qtd_nulos  qtd_valores_unicos
0                       cd_pleito        object          0                3364
1                 nu_processo_sei        object       2454                1027
2                       nm_pleito        object          1                3248
3                       sg_pleito        object        393                2925
4                   nm_proponente        object          0                 488
5                de_tipo_operacao        object          0                   7
6                         de_fase        object          0                   8
7                        de_fonte        object        283                 115
8                        sg_fonte        object        284                 112
9                        nm_moeda        object        283                   7
10         vl_financiamento_dolar       float64        283                1515
11         vl_contrapartida_dolar       float64       1059                1262
12                      de_esfera        object        289                   4
13                      nm_regiao        object          0                   6
14                          nm_uf        object         26                  28
15                          sg_uf        object         26                  28
16          dt_ultimo_recebimento        object        406                1717
17             dt_primeira_cofiex        object       1630                 394
18       dt_validade_recomendacao        object       2554                 290
19          dt_reuniao_negociacao        object       2630                 830
20              dt_publicacao_dou        object       2456                 219
21                  dt_assinatura        object       2132                1106
22  dt_ultimo_desembolso_original        object       2310                 804
23   dt_ultimo_desembolso_vigente        object       2136                 895
24                    nu_operacao        object       2145                1338

In [32]:
colunas_data = [coluna for coluna in df_raw.columns if coluna.startswith("dt_")]

colunas_data

['dt_ultimo_recebimento',
 'dt_primeira_cofiex',
 'dt_validade_recomendacao',
 'dt_reuniao_negociacao',
 'dt_publicacao_dou',
 'dt_assinatura',
 'dt_ultimo_desembolso_original',
 'dt_ultimo_desembolso_vigente']

In [33]:
relatorio_datas_ausentes = (
    df_raw[colunas_data]
    .isna()
    .sum()
    .reset_index()
    .rename(columns={
        "index": "coluna",
        0: "qtd_nulos"
    })
)

relatorio_datas_ausentes["percentual_nulos"] = (
    relatorio_datas_ausentes["qtd_nulos"] / len(df_raw) * 100
).round(2)

relatorio_datas_ausentes = relatorio_datas_ausentes.sort_values(
    by="percentual_nulos",
    ascending=False
)

relatorio_datas_ausentes

                          coluna  qtd_nulos  percentual_nulos
3          dt_reuniao_negociacao       2630             74.13
2       dt_validade_recomendacao       2554             71.98
4              dt_publicacao_dou       2456             69.22
6  dt_ultimo_desembolso_original       2310             65.11
7   dt_ultimo_desembolso_vigente       2136             60.20
5                  dt_assinatura       2132             60.09
1             dt_primeira_cofiex       1630             45.94
0          dt_ultimo_recebimento        406             11.44

In [34]:
print(f"Quantidade de colunas de data: {len(colunas_data)}")
print("Colunas de data encontradas:")
print(colunas_data)

Quantidade de colunas de data: 8
Colunas de data encontradas:
['dt_ultimo_recebimento', 'dt_primeira_cofiex', 'dt_validade_recomendacao', 'dt_reuniao_negociacao', 'dt_publicacao_dou', 'dt_assinatura', 'dt_ultimo_desembolso_original', 'dt_ultimo_desembolso_vigente']

In [35]:
datas_min_max = []

for coluna in colunas_data:
    serie_data = pd.to_datetime(df_raw[coluna], errors="coerce")
    
    datas_min_max.append({
        "coluna": coluna,
        "data_minima": serie_data.min(),
        "data_maxima": serie_data.max(),
        "qtd_datas_invalidas_ou_nulas": serie_data.isna().sum()
    })

datas_min_max = pd.DataFrame(datas_min_max)

datas_min_max

,coluna,data_minima,data_maxima,qtd_datas_invalidas_ou_nulas
0,dt_ultimo_recebimento,1940-01-01,2026-03-23,406
1,dt_primeira_cofiex,1990-05-30,2026-04-01,1630
2,dt_validade_recomendacao,2000-09-11,2027-12-22,2555
3,dt_reuniao_negociacao,1989-11-07,2026-04-01,2630
4,dt_publicacao_dou,1998-06-24,2025-11-21,2456
5,dt_assinatura,1949-01-27,2025-12-30,2132
6,dt_ultimo_desembolso_original,1986-12-31,2228-03-29,2311
7,dt_ultimo_desembolso_vigente,1953-12-31,2225-01-01,2136

In [36]:
datas_min_max["data_minima"] = datas_min_max["data_minima"].dt.date
datas_min_max["data_maxima"] = datas_min_max["data_maxima"].dt.date

datas_min_max

,coluna,data_minima,data_maxima,qtd_datas_invalidas_ou_nulas
0,dt_ultimo_recebimento,1940-01-01,2026-03-23,406
1,dt_primeira_cofiex,1990-05-30,2026-04-01,1630
2,dt_validade_recomendacao,2000-09-11,2027-12-22,2555
3,dt_reuniao_negociacao,1989-11-07,2026-04-01,2630
4,dt_publicacao_dou,1998-06-24,2025-11-21,2456
5,dt_assinatura,1949-01-27,2025-12-30,2132
6,dt_ultimo_desembolso_original,1986-12-31,2228-03-29,2311
7,dt_ultimo_desembolso_vigente,1953-12-31,2225-01-01,2136

In [37]:
qtd_financiamento_nulo = df_raw["vl_financiamento_dolar"].isna().sum()
qtd_financiamento_zero = (df_raw["vl_financiamento_dolar"] == 0).sum()
qtd_financiamento_nulo_ou_zero = (
    df_raw["vl_financiamento_dolar"].isna()
    | (df_raw["vl_financiamento_dolar"] == 0)
).sum()

print(f"Financiamento nulo: {qtd_financiamento_nulo}")
print(f"Financiamento zero: {qtd_financiamento_zero}")
print(f"Financiamento nulo ou zero: {qtd_financiamento_nulo_ou_zero}")

Financiamento nulo: 283
Financiamento zero: 29
Financiamento nulo ou zero: 312

In [38]:
percentual_financiamento_nulo = round(qtd_financiamento_nulo / len(df_raw) * 100, 2)
percentual_financiamento_zero = round(qtd_financiamento_zero / len(df_raw) * 100, 2)
percentual_financiamento_nulo_ou_zero = round(qtd_financiamento_nulo_ou_zero / len(df_raw) * 100, 2)

print(f"Percentual financiamento nulo: {percentual_financiamento_nulo}%")
print(f"Percentual financiamento zero: {percentual_financiamento_zero}%")
print(f"Percentual financiamento nulo ou zero: {percentual_financiamento_nulo_ou_zero}%")

Percentual financiamento nulo: 7.98%
Percentual financiamento zero: 0.82%
Percentual financiamento nulo ou zero: 8.79%

In [39]:
df_financiamento_nulo_ou_zero = df_raw[
    df_raw["vl_financiamento_dolar"].isna()
    | (df_raw["vl_financiamento_dolar"] == 0)
]

df_financiamento_nulo_ou_zero.head()

,cd_pleito,nu_processo_sei,nm_pleito,sg_pleito,nm_proponente,de_tipo_operacao,de_fase,de_fonte,sg_fonte,nm_moeda,...,sg_uf,dt_ultimo_recebimento,dt_primeira_cofiex,dt_validade_recomendacao,dt_reuniao_negociacao,dt_publicacao_dou,dt_assinatura,dt_ultimo_desembolso_original,dt_ultimo_desembolso_vigente,nu_operacao
210,57900,NaN,Ensino Superior de Santa Catarina,ENS. SUP/SC,Estado de Santa Catarina,Operação de crédito externo,Arquivado,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,SC,1940-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,57901,NaN,Apoio ao Ensino Superior Como Base do Des. Soc...,ENS. SUP/SP,Estado de São Paulo,Operação de crédito externo,Arquivado,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,SP,1940-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,57903,NaN,Projeto Guanabara,PROJETO GUANABARA,Estado do Rio de Janeiro,Operação de crédito externo,Arquivado,NaN,NaN,NaN,...,RJ,1940-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,57924,NaN,Desenvolvimento Urbano de Belo Horizonte,URBANO BELO HORIZONTE,Município de Belo Horizonte - MG,Operação de crédito externo,Arquivado,Banco Interamericano de Desenvolvimento - BID,BID,Dólar,...,MG,1940-01-01,1990-10-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,57925,NaN,Programa Nacional de Saneamento Rural,SANEAMENTO RURAL,República Federativa do Brasil,Operação de crédito externo,Arquivado,Banco Internacional para Reconstrução e Desenv...,BIRD,Dólar,...,DF,1990-07-18,1990-09-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
qtd_contrapartida_nula = df_raw["vl_contrapartida_dolar"].isna().sum()

qtd_contrapartida_nula

np.int64(1059)

In [41]:
percentual_contrapartida_nula = round(
    qtd_contrapartida_nula / len(df_raw) * 100,
    2
)

print(f"Contrapartida nula: {qtd_contrapartida_nula}")
print(f"Percentual contrapartida nula: {percentual_contrapartida_nula}%")

Contrapartida nula: 1059
Percentual contrapartida nula: 29.85%

In [42]:
qtd_contrapartida_nula = df_raw["vl_contrapartida_dolar"].isna().sum()

qtd_contrapartida_nula

np.int64(1059)

In [43]:
percentual_contrapartida_nula = round(
    qtd_contrapartida_nula / len(df_raw) * 100,
    2
)

print(f"Contrapartida nula: {qtd_contrapartida_nula}")
print(f"Percentual contrapartida nula: {percentual_contrapartida_nula}%")

Contrapartida nula: 1059
Percentual contrapartida nula: 29.85%

In [44]:
qtd_contrapartida_maior_financiamento = (
    df_raw["vl_contrapartida_dolar"] > df_raw["vl_financiamento_dolar"]
).sum()

qtd_contrapartida_maior_financiamento

np.int64(338)

In [45]:
percentual_contrapartida_maior_financiamento = round(
    qtd_contrapartida_maior_financiamento / len(df_raw) * 100,
    2
)

print(
    "Registros com contrapartida maior que financiamento:",
    qtd_contrapartida_maior_financiamento
)

print(
    "Percentual:",
    f"{percentual_contrapartida_maior_financiamento}%"
)

Registros com contrapartida maior que financiamento: 338
Percentual: 9.53%

In [46]:
categorias_esfera = (
    df_raw["de_esfera"]
    .value_counts(dropna=False)
    .rename_axis("categoria")
    .reset_index(name="qtd_registros")
)

categorias_esfera["percentual"] = (
    categorias_esfera["qtd_registros"] / len(df_raw) * 100
).round(2)

categorias_esfera

   categoria  qtd_registros  percentual
0   Estadual           1330       37.49
1    Federal           1218       34.33
2  Municipal            711       20.04
3        NaN            289        8.15

In [47]:
print(f"Quantidade de categorias em de_esfera: {df_raw['de_esfera'].nunique(dropna=False)}")

Quantidade de categorias em de_esfera: 4

In [48]:
categorias_moeda = (
    df_raw["nm_moeda"]
    .value_counts(dropna=False)
    .rename_axis("categoria")
    .reset_index(name="qtd_registros")
)

categorias_moeda["percentual"] = (
    categorias_moeda["qtd_registros"] / len(df_raw) * 100
).round(2)

categorias_moeda

  categoria  qtd_registros  percentual
0     Dólar           2983       84.08
1       NaN            283        7.98
2      Euro            166        4.68
3      Real             86        2.42
4       SDR             17        0.48
5      Iene             12        0.34
6     Libra              1        0.03

In [49]:
relatorio_qualidade_colunas = pd.DataFrame({
    "coluna": df_raw.columns,
    "tipo_inferido": df_raw.dtypes.astype(str).values,
    "qtd_nulos": df_raw.isna().sum().values,
    "percentual_nulos": (df_raw.isna().sum().values / len(df_raw) * 100).round(2),
    "qtd_valores_unicos": df_raw.nunique(dropna=False).values,
    "percentual_unicos": (df_raw.nunique(dropna=False).values / len(df_raw) * 100).round(2)
})

relatorio_qualidade_colunas = relatorio_qualidade_colunas.sort_values(
    by="percentual_nulos",
    ascending=False
)

relatorio_qualidade_colunas

,coluna,tipo_inferido,qtd_nulos,percentual_nulos,qtd_valores_unicos,percentual_unicos
19,dt_reuniao_negociacao,object,2630,74.13,830,23.39
18,dt_validade_recomendacao,object,2554,71.98,290,8.17
20,dt_publicacao_dou,object,2456,69.22,219,6.17
1,nu_processo_sei,object,2454,69.17,1027,28.95
22,dt_ultimo_desembolso_original,object,2310,65.11,804,22.66
24,nu_operacao,object,2145,60.46,1338,37.71
23,dt_ultimo_desembolso_vigente,object,2136,60.20,895,25.23
21,dt_assinatura,object,2132,60.09,1106,31.17
17,dt_primeira_cofiex,object,1630,45.94,394,11.10
11,vl_contrapartida_dolar,float64,1059,29.85,1262,35.57
16,dt_ultimo_recebimento,object,406,11.44,1717,48.39
3,sg_pleito,object,393,11.08,2925,82.44
12,de_esfera,object,289,8.15,4,0.11
8,sg_fonte,object,284,8.00,112,3.16
10,vl_financiamento_dolar,float64,283,7.98,1515,42.70
9,nm_moeda,object,283,7.98,7,0.20
7,de_fonte,object,283,7.98,115,3.24
14,nm_uf,object,26,0.73,28,0.79
15,sg_uf,object,26,0.73,28,0.79
2,nm_pleito,object,1,0.03,3248,91.54
13,nm_regiao,object,0,0.00,6,0.17
6,de_fase,object,0,0.00,8,0.23
5,de_tipo_operacao,object,0,0.00,7,0.20
4,nm_proponente,object,0,0.00,488,13.75
0,cd_pleito,object,0,0.00,3364,94.81

In [50]:
colunas_auditoria_cd_pleito = [
    "cd_pleito",
    "nu_operacao",
    "nm_pleito",
    "nm_proponente",
    "de_tipo_operacao",
    "de_fase",
    "de_fonte",
    "sg_fonte",
    "vl_financiamento_dolar",
    "vl_contrapartida_dolar",
    "dt_ultimo_recebimento",
    "dt_primeira_cofiex",
    "dt_assinatura",
    "dt_ultimo_desembolso_vigente"
]

In [51]:
exemplos_cd_pleito_repetidos = (
    df_cd_pleito_repetidos[colunas_auditoria_cd_pleito]
    .head(30)
)

exemplos_cd_pleito_repetidos

,cd_pleito,nu_operacao,nm_pleito,nm_proponente,de_tipo_operacao,de_fase,de_fonte,sg_fonte,vl_financiamento_dolar,vl_contrapartida_dolar,dt_ultimo_recebimento,dt_primeira_cofiex,dt_assinatura,dt_ultimo_desembolso_vigente
3,120,3138,Programa de Consolidação do Equilíbrio Fiscal ...,Estado do Rio Grande do Sul,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,200000000.0,NaN,2012-09-14,2013-10-04,2014-05-29,2016-05-29
4,120,8379,Programa de Consolidação do Equilíbrio Fiscal ...,Estado do Rio Grande do Sul,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,280000000.0,NaN,2012-09-14,2013-10-04,2014-08-20,2015-12-31
3445,176200631/2025,NaN,PROGRAMA DE DESENVOLVIMENTO URBANO NO MUNICÍPI...,Município de Petrolina,Operação de crédito externo,Aprovado,Fundo da Organização dos Países Exportadores d...,Fundo OPEP,60000000.0,15000000.0,2025-02-25,2025-03-27,NaN,NaN
3444,176200631/2025,NaN,PROGRAMA DE DESENVOLVIMENTO URBANO NO MUNICÍPI...,Município de Petrolina,Operação de crédito externo,Aprovado,Fundo Financeiro para o Desenvolvimento da Bac...,FONPLATA,20000000.0,5000000.0,2025-02-25,2025-03-27,NaN,NaN
3448,1943105475/2025,NaN,Parque Tecnológico de Brasília – BIOTIC: Infra...,BIOTIC S.A.,Operação de crédito externo,Aprovado,Fundo da Organização dos Países Exportadores d...,Fundo OPEP,60000000.0,0.0,2025-08-08,2025-09-18,NaN,NaN
3447,1943105475/2025,NaN,Parque Tecnológico de Brasília – BIOTIC: Infra...,BIOTIC S.A.,Operação de crédito externo,Aprovado,Fundo Financeiro para o Desenvolvimento da Bac...,FONPLATA,55000000.0,0.0,2025-08-08,2025-09-18,NaN,NaN
3465,3511351018/2025,NaN,Programa BNDES-BIRD de Apoio ao Arco da Restau...,Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Aprovado,Banco Internacional para Reconstrução e Desenv...,BIRD/CIF,47000000.0,0.0,2025-02-25,2025-03-27,NaN,NaN
3464,3511351018/2025,NaN,Programa BNDES-BIRD de Apoio ao Arco da Restau...,Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Aprovado,Banco Internacional para Reconstrução e Desenv...,BIRD,100000000.0,100000000.0,2025-02-25,2025-03-27,NaN,NaN
3470,4106356693/2025,NaN,Programa de Financiamento da Modernização da I...,Ministério das Comunicações,Operação de crédito externo,Aprovado,Banco Internacional para Reconstrução e Desenv...,BIRD,250000000.0,0.0,2025-11-04,2025-12-11,NaN,NaN
3469,4106356693/2025,NaN,Programa de Financiamento da Modernização da I...,Ministério das Comunicações,Operação de crédito externo,Aprovado,Banco Interamericano de Desenvolvimento - BID,BID,250000000.0,0.0,2025-11-04,2025-12-11,NaN,NaN
3480,5384019907/2025,NaN,PROGRAMA JOINVILLE RESILIENTE E SUSTENTÁVEL: I...,Município de Joinville,Operação de crédito externo,Aprovado,Fundo da Organização dos Países Exportadores d...,Fundo OPEP,65000000.0,22500000.0,2025-07-10,2025-09-18,NaN,NaN
3479,5384019907/2025,NaN,PROGRAMA JOINVILLE RESILIENTE E SUSTENTÁVEL: I...,Município de Joinville,Operação de crédito externo,Aprovado,Fundo Financeiro para o Desenvolvimento da Bac...,FONPLATA,25000000.0,0.0,2025-07-10,2025-09-18,NaN,NaN
3482,5492643979/2024,NaN,Melhoria da Sustentabilidade da Dívida do Esta...,Estado de São Paulo,Operação de crédito externo,Aprovado,Banco Internacional para Reconstrução e Desenv...,BIRD/MIGA,305000000.0,0.0,2025-02-21,2025-03-27,NaN,NaN
3481,5492643979/2024,NaN,Melhoria da Sustentabilidade da Dívida do Esta...,Estado de São Paulo,Operação de crédito externo,Aprovado,Banco Internacional para Reconstrução e Desenv...,BIRD,970000000.0,0.0,2025-02-21,2025-03-27,NaN,NaN
39,57754,0892-FOE,Saneamento Básico de Fortaleza - SANEFOR,Estado do Ceará,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID/...,BID,39900000.0,0.0,1992-02-07,1991-06-05,1992-12-09,1998-09-09
38,57754,0695-CO,Saneamento Básico de Fortaleza - SANEFOR,Estado do Ceará,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,159300000.0,0.0,1992-02-07,1991-06-05,1992-12-09,1998-09-09
60,57775,3714-0,Programa Gerenciamento Malha Rodoviária de Toc...,Estado do Tocantins,Operação de crédito externo,Finalizada,Banco Internacional para Reconstrução e Desenv...,BIRD,87000000.0,87600000.0,1991-06-26,1995-09-18,1994-06-24,1999-12-31
61,57775,NaN,Programa Gerenciamento Malha Rodoviária de Toc...,Estado do Tocantins,Operação de crédito externo,Repagamento,Banco do Japão para Cooperação Internacional -...,JBIC,48000000.0,87600000.0,1991-06-26,1995-09-18,1997-03-17,1999-12-31
64,57777,4188-0,Reabilitação e Descentralização de Rodovias Fe...,República Federativa do Brasil,Operação de crédito externo,Finalizada,Banco Internacional para Reconstrução e Desenv...,BIRD,300000000.0,150000000.0,1991-06-25,1991-07-11,1997-12-10,2005-12-17
63,57777,1046/CO-BR,Reabilitação e Descentralização de Rodovias Fe...,República Federativa do Brasil,Operação de crédito externo,Finalizada,Banco Interamericano de Desenvolvimento - BID,BID,300000000.0,150000000.0,1991-06-25,1991-07-11,1998-03-15,2007-03-15
66,57778,0776-CO,Recuperação Bacia do Guaíba - PRÓ-GUAÍBA,Estado do Rio Grande do Sul,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,110200000.0,0.0,1999-12-09,1993-06-02,1995-07-26,2001-07-26
65,57778,911/SF-BR,Recuperação Bacia do Guaíba - PRÓ-GUAÍBA,Estado do Rio Grande do Sul,Operação de crédito externo,Finalizada,Banco Interamericano de Desenvolvimento - BID/...,BID,22100000.0,0.0,1999-12-09,1993-06-02,1995-07-26,2002-07-26
69,57780,NaN,Programa Multisetorial de Credito,Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Arquivado,Banco do Japão para Cooperação Internacional -...,JBIC,250000000.0,0.0,1991-06-27,1990-12-19,NaN,1996-05-15
68,57780,0602-CO,Programa Multisetorial de Credito,Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Finalizada,Banco Interamericano de Desenvolvimento - BID,BID,250000000.0,0.0,1991-06-27,1990-12-19,1991-07-15,1996-05-15
71,57782,0503-CO,Pav.Rio Branco/Porto V.Pmaci,República Federativa do Brasil,Operação de crédito externo,Finalizada,Banco Interamericano de Desenvolvimento - BID,BID,14500000.0,0.0,1940-01-01,NaN,1985-03-14,1995-05-14
72,57782,150-CI,Pav.Rio Branco/Porto V.Pmaci,República Federativa do Brasil,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,44000000.0,0.0,1940-01-01,NaN,1985-03-14,1995-05-14
73,57783,3173-0,PNMA - Programa Nacional Do Meio Ambiente,República Federativa do Brasil,Operação de crédito externo,Finalizada,Banco Internacional para Reconstrução e Desenv...,BIRD,117000000.0,0.0,1940-01-01,1990-06-21,1990-08-16,2000-12-31
74,57783,NaN,PNMA - Programa Nacional Do Meio Ambiente,República Federativa do Brasil,Operação de crédito externo,Repagamento,KfW Entwicklungsbank,KfW,20000000.0,0.0,1940-01-01,1990-06-21,1992-10-02,2000-12-31
98,57807,0573-CO,Irrigação Nordeste,República Federativa do Brasil,Operação de crédito externo,Finalizada,Banco Interamericano de Desenvolvimento - BID,BID,55600000.0,38400000.0,1990-07-25,NaN,1990-01-10,1998-01-10
99,57807,BZ--P5,Irrigação Nordeste,República Federativa do Brasil,Operação de crédito externo,Repagamento,Agência de Cooperação Internacional do Japão -...,JICA,56600000.0,38400000.0,1990-07-25,NaN,1991-09-05,1998-12-26

In [52]:
top_cd_pleito_repetidos = (
    df_raw["cd_pleito"]
    .value_counts()
    .loc[lambda x: x > 1]
    .head(20)
    .reset_index()
    .rename(columns={
        "cd_pleito": "qtd_ocorrencias",
        "index": "cd_pleito"
    })
)

top_cd_pleito_repetidos

   qtd_ocorrencias  count
0            58421      7
1            60723      6
2            57947      4
3            58500      3
4            58623      3
5            58303      3
6            57862      3
7            59877      3
8            58661      3
9            58494      3
10           58496      3
11           60615      3
12           60374      3
13           57814      3
14           58505      3
15           58433      3
16           58480      3
17           60708      3
18           57837      2
19           57838      2

In [53]:
colunas_valores = [
    "vl_financiamento_dolar",
    "vl_contrapartida_dolar"
]

df_raw[colunas_valores].dtypes

vl_financiamento_dolar    float64
vl_contrapartida_dolar    float64
dtype: object

In [54]:
df_raw[colunas_valores].head(20).style.format({
    "vl_financiamento_dolar": "{:,.0f}",
    "vl_contrapartida_dolar": "{:,.0f}"
})

In [55]:
for coluna in colunas_valores:
    qtd_com_decimal = (
        df_raw[coluna]
        .dropna()
        .mod(1)
        .ne(0)
        .sum()
    )
    
    print(f"{coluna}: {qtd_com_decimal} valores com casas decimais reais")

vl_financiamento_dolar: 193 valores com casas decimais reais
vl_contrapartida_dolar: 137 valores com casas decimais reais

In [56]:
resumo_valores = df_raw[colunas_valores].describe().T

resumo_valores.style.format("{:,.2f}")

In [57]:
colunas_auditoria_valores = [
    "cd_pleito",
    "nm_pleito",
    "nm_proponente",
    "de_tipo_operacao",
    "de_fase",
    "de_fonte",
    "sg_fonte",
    "vl_financiamento_dolar",
    "vl_contrapartida_dolar"
]

df_raw.nlargest(10, "vl_financiamento_dolar")[colunas_auditoria_valores]

,cd_pleito,nm_pleito,nm_proponente,de_tipo_operacao,de_fase,de_fonte,sg_fonte,vl_financiamento_dolar,vl_contrapartida_dolar
2376,60090,Projeto F-X2 Aquisição de Aeronaves de Caça e...,República Federativa do Brasil,Operação Comercial,Em execução,Swedish Export Credit Corporation,AB SEK,5.734219e+09,NaN
2654,60434,O Projeto de Construção da Ponte Salvador - Il...,"China Tiesiju Civil Engineering Group Co., LTD",Outros,Arquivado,Instituições Chinesas/Chinese Institutions,Ch_Inst,5.678250e+09,1.892750e+09
1971,59663,Programa de Desenvolvimento de Submarinos - PR...,República Federativa do Brasil,Operação Comercial,Em execução,Consórcio de Bancos,Consórcio de Bancos,5.558206e+09,4.074508e+09
2716,60511,Refinaria do Maranhão,Refinaria Petroquímica Brasil S.A.,Outros,Arquivado,Dívida / Debt Investment,Debt Investment,4.000000e+09,NaN
1990,59683,Aquisição de helicópteros de médio porte para ...,República Federativa do Brasil,Operação Comercial,Em execução,Consórcio Bancário liderado pelo Societé Generale,SOCIETÉ GENERALE,2.580180e+09,1.218892e+08
942,58619,Programa de Reforma e Proteção Social,República Federativa do Brasil,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,2.200000e+09,NaN
2086,59777,"Projeto Construção, Montagem e Comissionamento...",Centrais Elétricas Brasileiras S/A - ELETROBRÁS,Operação de crédito externo,Arquivado,Consórcio Bancário liderado pelo Societé Generale,SOCIETÉ GENERALE,2.100000e+09,4.236089e+09
415,58107,Corredor de Transporte Multimodal Centro-Norte...,República Federativa do Brasil,Operação de crédito externo,Arquivado,Banco Internacional para Reconstrução e Desenv...,BIRD,1.848000e+09,3.630000e+08
2705,60500,XINGU RIO TRANSMISSORA DE ENERGIA - XRTE,XINGU RIO TRANSMISSORA DE ENERGIA S.A.,Outros,Arquivado,Dívida / Debt Investment,Debt Investment,1.818991e+09,NaN
208,57898,Saneamento e Meio-Amb. na Areado Mercosul,Caixa Econômica Federal - CEF,Operação de crédito externo,Arquivado,Banco Internacional para Reconstrução e Desenv...,BIRD,1.760347e+09,0.000000e+00

In [58]:
df_raw.nlargest(10, "vl_contrapartida_dolar")[colunas_auditoria_valores]

,cd_pleito,nm_pleito,nm_proponente,de_tipo_operacao,de_fase,de_fonte,sg_fonte,vl_financiamento_dolar,vl_contrapartida_dolar
1944,59637,Consolidação do Programa Bolsa Família e Apoio...,República Federativa do Brasil,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,2.000000e+08,1.001500e+10
1763,59454,Programa Integrado de Melhoria Ambiental na Ár...,Companhia de Saneamento Básico do Estado de Sã...,Operação de crédito externo,Arquivado,NaN,NaN,NaN,6.208000e+09
1792,59482,Projeto de Apoio a Inclusão Social e Crescimen...,Estado do Ceará,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,2.400000e+08,4.560000e+09
2086,59777,"Projeto Construção, Montagem e Comissionamento...",Centrais Elétricas Brasileiras S/A - ELETROBRÁS,Operação de crédito externo,Arquivado,Consórcio Bancário liderado pelo Societé Generale,SOCIETÉ GENERALE,2.100000e+09,4.236089e+09
1971,59663,Programa de Desenvolvimento de Submarinos - PR...,República Federativa do Brasil,Operação Comercial,Em execução,Consórcio de Bancos,Consórcio de Bancos,5.558206e+09,4.074508e+09
1809,59499,Programa de Parceria para o Desenvolvimento de...,Estado de Minas Gerais,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,9.760000e+08,3.060432e+09
2608,60391,FERROVIA PARAENSE,Governo do Estado do Pará,Outros,Arquivado,Instituições Chinesas/Chinese Institutions,Ch_Inst,1.650514e+09,2.285328e+09
1772,59462,"Programa BNDES de Apoio às Micro, Pequenas e M...",Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,1.000000e+09,2.000000e+09
2654,60434,O Projeto de Construção da Ponte Salvador - Il...,"China Tiesiju Civil Engineering Group Co., LTD",Outros,Arquivado,Instituições Chinesas/Chinese Institutions,Ch_Inst,5.678250e+09,1.892750e+09
2074,59766,Rodoanel Mario Covas - Trecho Norte - 1ª Fase,Estado de São Paulo,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,1.148633e+09,1.866600e+09

In [59]:
df_outliers_financeiros = df_raw.copy()

df_outliers_financeiros["razao_contrapartida_financiamento"] = (
    df_outliers_financeiros["vl_contrapartida_dolar"]
    / df_outliers_financeiros["vl_financiamento_dolar"]
)

df_outliers_financeiros.nlargest(
    20,
    "vl_contrapartida_dolar"
)[
    colunas_auditoria_valores + ["razao_contrapartida_financiamento"]
]

,cd_pleito,nm_pleito,nm_proponente,de_tipo_operacao,de_fase,de_fonte,sg_fonte,vl_financiamento_dolar,vl_contrapartida_dolar,razao_contrapartida_financiamento
1944,59637,Consolidação do Programa Bolsa Família e Apoio...,República Federativa do Brasil,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,2.000000e+08,1.001500e+10,50.075000
1763,59454,Programa Integrado de Melhoria Ambiental na Ár...,Companhia de Saneamento Básico do Estado de Sã...,Operação de crédito externo,Arquivado,NaN,NaN,NaN,6.208000e+09,NaN
1792,59482,Projeto de Apoio a Inclusão Social e Crescimen...,Estado do Ceará,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,2.400000e+08,4.560000e+09,19.000000
2086,59777,"Projeto Construção, Montagem e Comissionamento...",Centrais Elétricas Brasileiras S/A - ELETROBRÁS,Operação de crédito externo,Arquivado,Consórcio Bancário liderado pelo Societé Generale,SOCIETÉ GENERALE,2.100000e+09,4.236089e+09,2.017185
1971,59663,Programa de Desenvolvimento de Submarinos - PR...,República Federativa do Brasil,Operação Comercial,Em execução,Consórcio de Bancos,Consórcio de Bancos,5.558206e+09,4.074508e+09,0.733062
1809,59499,Programa de Parceria para o Desenvolvimento de...,Estado de Minas Gerais,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,9.760000e+08,3.060432e+09,3.135689
2608,60391,FERROVIA PARAENSE,Governo do Estado do Pará,Outros,Arquivado,Instituições Chinesas/Chinese Institutions,Ch_Inst,1.650514e+09,2.285328e+09,1.384615
1772,59462,"Programa BNDES de Apoio às Micro, Pequenas e M...",Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,1.000000e+09,2.000000e+09,2.000000
2654,60434,O Projeto de Construção da Ponte Salvador - Il...,"China Tiesiju Civil Engineering Group Co., LTD",Outros,Arquivado,Instituições Chinesas/Chinese Institutions,Ch_Inst,5.678250e+09,1.892750e+09,0.333333
2074,59766,Rodoanel Mario Covas - Trecho Norte - 1ª Fase,Estado de São Paulo,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,1.148633e+09,1.866600e+09,1.625062
2868,60682,Programa de Apoio ao Plano de Investimento SABESP,Companhia de Saneamento Básico do Estado de Sã...,Operação de crédito externo,Negociação concluída,New Development Bank - NDB,NDB,3.000000e+08,1.865000e+09,6.216667
1824,59514,Programa de Apoio ao Desenvolvimento das Micro...,Banco do Brasil S/A,Operação de crédito externo,Arquivado,Banco Interamericano de Desenvolvimento - BID,BID,1.500000e+09,1.500000e+09,1.000000
1969,59661,"""Expansão da Linha 5 - Lilás do Metrô de São P...",Estado de São Paulo,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,6.504140e+08,1.353828e+09,2.081487
2016,59708,Programa de Parceria para o Desenvolvimento de...,Estado de Minas Gerais,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,4.610000e+08,1.319009e+09,2.861191
2105,59797,Rodoanel Mario Covas - Trecho Norte - 2ª Fase,Estado de São Paulo,Operação de crédito externo,Arquivado,Banco Interamericano de Desenvolvimento - BID,BID,7.486330e+08,1.216575e+09,1.625062
1563,59256,Projeto de Ampliação de Capacidade e Melhorame...,República Federativa do Brasil,Operação de crédito externo,Arquivado,Banco Interamericano de Desenvolvimento - BID,BID,1.000000e+08,1.190000e+09,11.900000
2316,60022,PIAUÍ - PILARES DE CRESCIMENTO E INCLUSÃO SOCI...,Estado do Piauí,Operação de crédito externo,Repagamento,Banco Internacional para Reconstrução e Desenv...,BIRD,1.200000e+08,1.118686e+09,9.322380
1300,58994,"Programa BNDES de Apoio às Micro, Pequenas e M...",Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,1.000000e+09,1.000000e+09,1.000000
1951,59645,Segundo Convênio de Linha de Crédito Condicion...,Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,1.000000e+09,1.000000e+09,1.000000
1087,58765,"Programa BNDES de Apoio às Micro, Pequenas e M...",Banco Nacional de Desenvolvimento Econômico e ...,Operação de crédito externo,Repagamento,Banco Interamericano de Desenvolvimento - BID,BID,9.000000e+08,9.000000e+08,1.000000

In [60]:
df_raw.loc[
    df_raw["vl_contrapartida_dolar"].idxmax(),
    [
        "cd_pleito",
        "nm_pleito",
        "nm_proponente",
        "vl_financiamento_dolar",
        "vl_contrapartida_dolar"
    ]
]

cd_pleito                                                             59637
nm_pleito                 Consolidação do Programa Bolsa Família e Apoio...
nm_proponente                                República Federativa do Brasil
vl_financiamento_dolar                                          200000000.0
vl_contrapartida_dolar                                        10015000000.0
Name: 1944, dtype: object

In [61]:
pd.options.display.float_format = "{:,.2f}".format

df_raw.nlargest(
    10,
    "vl_contrapartida_dolar"
)[
    [
        "cd_pleito",
        "nm_pleito",
        "nm_proponente",
        "vl_financiamento_dolar",
        "vl_contrapartida_dolar"
    ]
]

,cd_pleito,nm_pleito,nm_proponente,vl_financiamento_dolar,vl_contrapartida_dolar
1944,59637,Consolidação do Programa Bolsa Família e Apoio...,República Federativa do Brasil,"200,000,000.00","10,015,000,000.00"
1763,59454,Programa Integrado de Melhoria Ambiental na Ár...,Companhia de Saneamento Básico do Estado de Sã...,NaN,"6,208,000,000.00"
1792,59482,Projeto de Apoio a Inclusão Social e Crescimen...,Estado do Ceará,"240,000,000.00","4,560,000,000.00"
2086,59777,"Projeto Construção, Montagem e Comissionamento...",Centrais Elétricas Brasileiras S/A - ELETROBRÁS,"2,100,000,000.00","4,236,089,000.00"
1971,59663,Programa de Desenvolvimento de Submarinos - PR...,República Federativa do Brasil,"5,558,205,535.24","4,074,508,263.68"
1809,59499,Programa de Parceria para o Desenvolvimento de...,Estado de Minas Gerais,"976,000,000.00","3,060,432,000.00"
2608,60391,FERROVIA PARAENSE,Governo do Estado do Pará,"1,650,514,467.27","2,285,327,723.90"
1772,59462,"Programa BNDES de Apoio às Micro, Pequenas e M...",Banco Nacional de Desenvolvimento Econômico e ...,"1,000,000,000.00","2,000,000,000.00"
2654,60434,O Projeto de Construção da Ponte Salvador - Il...,"China Tiesiju Civil Engineering Group Co., LTD","5,678,250,000.00","1,892,750,000.00"
2074,59766,Rodoanel Mario Covas - Trecho Norte - 1ª Fase,Estado de São Paulo,"1,148,633,000.00","1,866,600,000.00"