In [58]:
from pathlib import Path

import numpy as np
import pandas as pd

In [59]:
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

ARQUIVO_BRUTO = BASE_DIR / "dados_brutos" / "dados_2026-04-14.xlsx"

df_raw = pd.read_excel(ARQUIVO_BRUTO, sheet_name="Dados")
df_tratado = df_raw.copy()

print(f"df_raw: {df_raw.shape}")
print(f"df_tratado: {df_tratado.shape}")

df_raw: (3548, 25)
df_tratado: (3548, 25)

In [60]:
df_tratado["de_tipo_operacao_padronizado"] = (
    df_tratado["de_tipo_operacao"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [61]:
mapa_tipo_operacao = {
    "Contribuição Financeira não Reembolsável GEF": "Contribuição financeira não reembolsável",
    "Contribuição financeira não reembolsável": "Contribuição financeira não reembolsável"
}

df_tratado["de_tipo_operacao_padronizado"] = (
    df_tratado["de_tipo_operacao_padronizado"]
    .replace(mapa_tipo_operacao)
)

In [62]:
df_tratado["de_tipo_operacao_padronizado"].value_counts(dropna=False)

de_tipo_operacao_padronizado
Operação de crédito externo                 2643
Doações                                      532
Contribuição financeira não reembolsável     288
Outros                                        64
Operação Comercial                            12
Cooperação Técnica GEF                         9
Name: count, dtype: Int64

In [63]:
colunas_texto = df_tratado.select_dtypes(include=["object", "string"]).columns

colunas_texto

Index(['cd_pleito', 'nu_processo_sei', 'nm_pleito', 'sg_pleito',
       'nm_proponente', 'de_tipo_operacao', 'de_fase', 'de_fonte', 'sg_fonte',
       'nm_moeda', 'de_esfera', 'nm_regiao', 'nm_uf', 'sg_uf',
       'dt_ultimo_recebimento', 'dt_primeira_cofiex',
       'dt_validade_recomendacao', 'dt_reuniao_negociacao',
       'dt_publicacao_dou', 'dt_assinatura', 'dt_ultimo_desembolso_original',
       'dt_ultimo_desembolso_vigente', 'nu_operacao',
       'de_tipo_operacao_padronizado'],
      dtype='object')

In [64]:
for coluna in colunas_texto:
    df_tratado[coluna] = (
        df_tratado[coluna]
        .astype("string")
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

In [65]:
df_tratado["de_fase_padronizado"] = (
    df_tratado["de_fase"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [66]:
mapa_fase = {}

df_tratado["de_fase_padronizado"] = (
    df_tratado["de_fase_padronizado"]
    .replace(mapa_fase)
)

In [67]:
df_tratado["de_fase_padronizado"].value_counts(dropna=False)

de_fase_padronizado
Arquivado               1587
Repagamento              706
Finalizada               598
Aprovado                 197
Reprovada                190
Em execução              168
Negociação concluída      95
Em negociação              7
Name: count, dtype: Int64

In [68]:
df_tratado["de_esfera_padronizado"] = (
    df_tratado["de_esfera"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [69]:
df_tratado["de_esfera_padronizado"] = (
    df_tratado["de_esfera_padronizado"]
    .fillna("Não informado")
)

In [70]:
df_tratado["de_esfera_padronizado"].value_counts(dropna=False)

de_esfera_padronizado
Estadual         1330
Federal          1218
Municipal         711
Não informado     289
Name: count, dtype: Int64

In [71]:
df_tratado["nm_regiao_padronizado"] = (
    df_tratado["nm_regiao"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [72]:
mapa_regiao = {}

df_tratado["nm_regiao_padronizado"] = (
    df_tratado["nm_regiao_padronizado"]
    .replace(mapa_regiao)
)

In [73]:
df_tratado["nm_regiao_padronizado"].value_counts(dropna=False)

nm_regiao_padronizado
Nacional        1087
Sudeste          844
Nordeste         618
Sul              472
Norte            270
Centro-Oeste     257
Name: count, dtype: Int64

In [74]:
df_tratado["sg_uf_padronizado"] = (
    df_tratado["sg_uf"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", "", regex=True)
)

In [75]:
df_tratado["sg_uf_padronizado"] = (
    df_tratado["sg_uf_padronizado"]
    .fillna("NAO_INFORMADO")
)

In [76]:
df_tratado["sg_fonte_padronizado"] = (
    df_tratado["sg_fonte"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)
)

In [77]:
df_tratado["sg_fonte_padronizado"] = (
    df_tratado["sg_fonte_padronizado"]
    .fillna("NAO_INFORMADO")
)

In [78]:
df_tratado["sg_uf_padronizado"].value_counts(dropna=False).head(30)

sg_uf_padronizado
DF               1134
SP                369
RJ                230
RS                211
MG                176
CE                160
SC                143
BA                120
PR                118
PE                 96
PA                 81
AM                 76
ES                 69
GO                 63
PI                 61
MS                 59
MA                 51
TO                 50
PB                 45
SE                 40
MT                 33
RN                 33
AL                 30
NAO_INFORMADO      26
AC                 26
RO                 22
AP                 18
RR                  8
Name: count, dtype: Int64

In [79]:
df_tratado["sg_fonte_padronizado"].value_counts(dropna=False).head(30)

sg_fonte_padronizado
BID              898
BIRD             812
NAO_INFORMADO    284
CAF              237
GEF              161
FONPLATA         139
JBIC              78
WB-JG             75
KFW               64
BID/FUMIN         63
FOCEM             52
NDB               51
AFD               45
GEF/PNUMA         40
GEF/BIRD          40
GEF/PNUD          37
PPG7              35
FIDA              32
BIRD/IDF          27
BID/JSF           25
CH_INST           25
KFW/DOAÇÃO        25
JICA              24
A DEFINIR         24
EU                14
ITALIA            14
BID/PRODEV        13
BEI               12
GEF/BID           11
AGROINVEST        10
Name: count, dtype: Int64

In [80]:
print(
    "Categorias sg_uf antes:",
    df_tratado["sg_uf"].nunique(dropna=False)
)

print(
    "Categorias sg_uf depois:",
    df_tratado["sg_uf_padronizado"].nunique(dropna=False)
)

print(
    "Categorias sg_fonte antes:",
    df_tratado["sg_fonte"].nunique(dropna=False)
)

print(
    "Categorias sg_fonte depois:",
    df_tratado["sg_fonte_padronizado"].nunique(dropna=False)
)

Categorias sg_uf antes: 28
Categorias sg_uf depois: 28
Categorias sg_fonte antes: 112
Categorias sg_fonte depois: 112

In [81]:
# Padronização de sg_fonte
df_tratado["sg_fonte_padronizado"] = (
    df_tratado["sg_fonte"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)
    .fillna("NAO_INFORMADO")
)

# Mapa de correções na coluna padronizada
mapa_sg_fonte = {
    "BID/ICSF": "BID/ICSTF",
}

df_tratado["sg_fonte_padronizado"] = (
    df_tratado["sg_fonte_padronizado"]
    .replace(mapa_sg_fonte)
)

# SECI: preencher sigla ausente com base na descrição
cond_seci = (
    (df_tratado["sg_fonte_padronizado"] == "NAO_INFORMADO")
    & df_tratado["de_fonte"].str.contains("SECI", na=False)
)
df_tratado.loc[cond_seci, "sg_fonte_padronizado"] = "SECI"

In [82]:
df_tratado["sg_fonte_padronizado"].value_counts(dropna=False)

sg_fonte_padronizado
BID              898
BIRD             812
NAO_INFORMADO    283
CAF              237
GEF              161
                ...
IBM                1
BID/FEC            1
BID/INWAP          1
GEF/FIDA           1
BIRD/MIGA          1
Name: count, Length: 112, dtype: Int64

In [83]:
# Tratar campos textuais vazios como nulos reais
colunas_texto = df_tratado.select_dtypes(include=["object", "string"]).columns

for coluna in colunas_texto:
    df_tratado[coluna] = (
        df_tratado[coluna]
        .replace(r"^\s*$", pd.NA, regex=True)
    )

In [84]:
df_tratado[colunas_texto].isna().sum()

cd_pleito                           0
nu_processo_sei                  2454
nm_pleito                           1
sg_pleito                         393
nm_proponente                       0
de_tipo_operacao                    0
de_fase                             0
de_fonte                          283
sg_fonte                          284
nm_moeda                          283
de_esfera                         289
nm_regiao                           0
nm_uf                              26
sg_uf                              26
dt_ultimo_recebimento             406
dt_primeira_cofiex               1630
dt_validade_recomendacao         2554
dt_reuniao_negociacao            2630
dt_publicacao_dou                2456
dt_assinatura                    2132
dt_ultimo_desembolso_original    2310
dt_ultimo_desembolso_vigente     2136
nu_operacao                      2146
de_tipo_operacao_padronizado        0
de_fase_padronizado                 0
de_esfera_padronizado               0
nm_regiao_padronizado               0
sg_uf_padronizado                   0
sg_fonte_padronizado                0
dtype: int64

In [85]:
# Criar flags para campos ausentes importantes
df_tratado["flag_sem_fonte"] = df_tratado["sg_fonte"].isna()
df_tratado["flag_sem_financiamento"] = df_tratado["vl_financiamento_dolar"].isna()
df_tratado["flag_sem_contrapartida"] = df_tratado["vl_contrapartida_dolar"].isna()
df_tratado["flag_sem_primeira_cofiex"] = df_tratado["dt_primeira_cofiex"].isna()
df_tratado["flag_sem_assinatura"] = df_tratado["dt_assinatura"].isna()

In [86]:
df_tratado[["flag_sem_fonte", "flag_sem_financiamento", "flag_sem_contrapartida",
            "flag_sem_primeira_cofiex", "flag_sem_assinatura"]].sum()

flag_sem_fonte               284
flag_sem_financiamento       283
flag_sem_contrapartida      1059
flag_sem_primeira_cofiex    1630
flag_sem_assinatura         2132
dtype: int64

In [87]:
# Preservar colunas originais de data antes da conversão
colunas_data = [
    "dt_ultimo_recebimento",
    "dt_primeira_cofiex",
    "dt_validade_recomendacao",
    "dt_reuniao_negociacao",
    "dt_publicacao_dou",
    "dt_assinatura",
    "dt_ultimo_desembolso_original",
    "dt_ultimo_desembolso_vigente",
]

for coluna in colunas_data:
    df_tratado[f"{coluna}_original"] = df_tratado[coluna].copy()

In [88]:
for coluna in colunas_data:
    df_tratado[coluna] = pd.to_datetime(df_tratado[coluna], errors="coerce")

In [89]:
df_tratado[colunas_data].dtypes

dt_ultimo_recebimento            datetime64[ns]
dt_primeira_cofiex               datetime64[ns]
dt_validade_recomendacao         datetime64[ns]
dt_reuniao_negociacao            datetime64[ns]
dt_publicacao_dou                datetime64[ns]
dt_assinatura                    datetime64[ns]
dt_ultimo_desembolso_original    datetime64[ns]
dt_ultimo_desembolso_vigente     datetime64[ns]
dtype: object

## Validacao das datas convertidas

Apos `pd.to_datetime(..., errors="coerce")`, conferir minimos, maximos e datas fora de faixa plausivel. Datas sentinela ou futuras extremas viram flag, nunca exclusao automatica.

In [90]:
# Resumo das datas apos conversao
resumo_datas = pd.DataFrame({
    "min": [df_tratado[c].min() for c in colunas_data],
    "max": [df_tratado[c].max() for c in colunas_data],
    "nulos": [df_tratado[c].isna().sum() for c in colunas_data],
}, index=colunas_data)

resumo_datas

                                     min        max  nulos
dt_ultimo_recebimento         1940-01-01 2026-03-23    406
dt_primeira_cofiex            1990-05-30 2026-04-01   1630
dt_validade_recomendacao      2000-09-11 2027-12-22   2555
dt_reuniao_negociacao         1989-11-07 2026-04-01   2630
dt_publicacao_dou             1998-06-24 2025-11-21   2456
dt_assinatura                 1949-01-27 2025-12-30   2132
dt_ultimo_desembolso_original 1986-12-31 2228-03-29   2311
dt_ultimo_desembolso_vigente  1953-12-31 2225-01-01   2136

In [91]:
# Datas fora de faixa plausivel (sentinela / futuras extremas)
# Faixa aceita: 1940-01-01 ate 2035-12-31 (horizonte razoavel de desembolso)
LIMITE_INFERIOR = pd.Timestamp("1940-01-01")
LIMITE_SUPERIOR = pd.Timestamp("2035-12-31")

for coluna in colunas_data:
    fora = (
        df_tratado[coluna].notna()
        & ((df_tratado[coluna] < LIMITE_INFERIOR) | (df_tratado[coluna] > LIMITE_SUPERIOR))
    )
    print(f"{coluna}: {fora.sum()} fora de faixa")

# Flag de data sentinela / fora de faixa (qualquer coluna de data)
mask_data_extrema = pd.Series(False, index=df_tratado.index)
for coluna in colunas_data:
    mask_data_extrema |= (
        df_tratado[coluna].notna()
        & ((df_tratado[coluna] < LIMITE_INFERIOR) | (df_tratado[coluna] > LIMITE_SUPERIOR))
    )

df_tratado["flag_data_extrema"] = mask_data_extrema
print("Total registros com data extrema:", df_tratado["flag_data_extrema"].sum())

dt_ultimo_recebimento: 0 fora de faixa
dt_primeira_cofiex: 0 fora de faixa
dt_validade_recomendacao: 0 fora de faixa
dt_reuniao_negociacao: 0 fora de faixa
dt_publicacao_dou: 0 fora de faixa
dt_assinatura: 0 fora de faixa
dt_ultimo_desembolso_original: 4 fora de faixa
dt_ultimo_desembolso_vigente: 4 fora de faixa
Total registros com data extrema: 5

## Garantir valores monetarios numericos

`vl_financiamento_dolar` e `vl_contrapartida_dolar` ja vieram como `float64`. Forcar conversao com `errors="coerce"` para garantir, sem arredondar (existem casas decimais reais).

In [92]:
colunas_financeiras = ["vl_financiamento_dolar", "vl_contrapartida_dolar"]

for coluna in colunas_financeiras:
    df_tratado[coluna] = pd.to_numeric(df_tratado[coluna], errors="coerce")

df_tratado[colunas_financeiras].dtypes

vl_financiamento_dolar    float64
vl_contrapartida_dolar    float64
dtype: object

In [93]:
# Conferencia: nenhum valor virou NaN por erro de conversao
for coluna in colunas_financeiras:
    print(f"{coluna}: nulos={df_tratado[coluna].isna().sum()}, min={df_tratado[coluna].min()}, max={df_tratado[coluna].max()}")

vl_financiamento_dolar: nulos=283, min=0.0, max=5734219058.95
vl_contrapartida_dolar: nulos=1059, min=0.0, max=10015000000.0

## Flag para valores financeiros nulos ou zero

`flag_sem_financiamento` ja marca nulos. Aqui criamos `flag_financiamento_nulo_zero` que cobre nulo OU zero, conforme o diagnostico (312 registros = 8,79%).

In [94]:
df_tratado["flag_financiamento_nulo_zero"] = (
    df_tratado["vl_financiamento_dolar"].isna()
    | (df_tratado["vl_financiamento_dolar"] == 0)
)

print("financiamento nulo:", df_tratado["vl_financiamento_dolar"].isna().sum())
print("financiamento zero:", (df_tratado["vl_financiamento_dolar"] == 0).sum())
print("nulo ou zero:", df_tratado["flag_financiamento_nulo_zero"].sum())

financiamento nulo: 283
financiamento zero: 29
nulo ou zero: 312

In [95]:
# Flag de contrapartida maior que financiamento (sinalizar, nao corrigir)
df_tratado["flag_contrapartida_maior_financiamento"] = (
    df_tratado["vl_contrapartida_dolar"].notna()
    & df_tratado["vl_financiamento_dolar"].notna()
    & (df_tratado["vl_contrapartida_dolar"] > df_tratado["vl_financiamento_dolar"])
)

print("contrapartida > financiamento:", df_tratado["flag_contrapartida_maior_financiamento"].sum())

contrapartida > financiamento: 338

## Flag para outliers financeiros

Criterio adotado (documentado): valor acima do percentil 99 em financiamento OU contrapartida, OU financiamento nulo/zero com contrapartida muito alta. Valores preservados, apenas sinalizados.

In [96]:
p99_fin = df_tratado["vl_financiamento_dolar"].quantile(0.99)
p99_contra = df_tratado["vl_contrapartida_dolar"].quantile(0.99)

print("percentil 99 financiamento:", p99_fin)
print("percentil 99 contrapartida:", p99_contra)

df_tratado["flag_outlier_financeiro"] = (
    (df_tratado["vl_financiamento_dolar"] > p99_fin)
    | (df_tratado["vl_contrapartida_dolar"] > p99_contra)
    | (
        df_tratado["flag_financiamento_nulo_zero"]
        & (df_tratado["vl_contrapartida_dolar"] > p99_contra)
    )
)

print("registros marcados como outlier financeiro:", df_tratado["flag_outlier_financeiro"].sum())

percentil 99 financiamento: 1000000000.0
percentil 99 contrapartida: 805451879.9999919
registros marcados como outlier financeiro: 47

## Padronizar nm_moeda

Strip, normalizacao de espacos e nulos como categoria auditavel `Nao informado`.

In [97]:
df_tratado["nm_moeda_padronizado"] = (
    df_tratado["nm_moeda"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .fillna("Não informado")
)

df_tratado["nm_moeda_padronizado"].value_counts(dropna=False)

nm_moeda_padronizado
Dólar            2983
Não informado     283
Euro              166
Real               86
SDR                17
Iene               12
Libra               1
Name: count, dtype: Int64

## Padronizar valores nulos categoricos como categoria auditavel

`de_esfera_padronizado`, `sg_uf_padronizado`, `sg_fonte_padronizado` e `nm_moeda_padronizado` ja tratam nulos. Falta `de_fonte`. Padronizamos com nulo explicito para auditoria.

In [98]:
df_tratado["de_fonte_padronizado"] = (
    df_tratado["de_fonte"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .fillna("Não informado")
)

# Conferencia das categorias auditaveis de nulo
print("de_esfera:", (df_tratado["de_esfera_padronizado"] == "Não informado").sum())
print("sg_uf:", (df_tratado["sg_uf_padronizado"] == "NAO_INFORMADO").sum())
print("sg_fonte:", (df_tratado["sg_fonte_padronizado"] == "NAO_INFORMADO").sum())
print("de_fonte:", (df_tratado["de_fonte_padronizado"] == "Não informado").sum())
print("nm_moeda:", (df_tratado["nm_moeda_padronizado"] == "Não informado").sum())

de_esfera: 289
sg_uf: 26
sg_fonte: 283
de_fonte: 283
nm_moeda: 283

## Validar que a limpeza nao alterou a quantidade de linhas

`df_tratado` deve manter as 3.548 linhas do `df_raw`. Nenhum registro removido.

In [99]:
assert len(df_tratado) == len(df_raw), "Quantidade de linhas mudou!"
assert df_tratado.index.equals(df_raw.index), "Indice mudou!"

print("df_raw linhas:", len(df_raw))
print("df_tratado linhas:", len(df_tratado))
print("colunas no df_tratado:", df_tratado.shape[1])
print("VALIDACAO OK: nenhuma linha removida")

df_raw linhas: 3548
df_tratado linhas: 3548
colunas no df_tratado: 50
VALIDACAO OK: nenhuma linha removida

In [100]:
# Resumo de todas as flags criadas
flags = [c for c in df_tratado.columns if c.startswith("flag_")]
df_tratado[flags].sum().sort_values(ascending=False)

flag_sem_assinatura                       2132
flag_sem_primeira_cofiex                  1630
flag_sem_contrapartida                    1059
flag_contrapartida_maior_financiamento     338
flag_financiamento_nulo_zero               312
flag_sem_fonte                             284
flag_sem_financiamento                     283
flag_outlier_financeiro                     47
flag_data_extrema                            5
dtype: int64

---
---

# ============================================================
# TRANSFORMACAO
# ============================================================

# A partir daqui comeca a etapa de TRANSFORMACAO

Tudo acima e **LIMPEZA**: padronizacao de categorias, tratamento textual, conversao de datas, valores numericos e flags de qualidade.

Tudo daqui para baixo e **TRANSFORMACAO**: tratamento de datas placeholder/sentinela, criacao de colunas derivadas (anos, valor total, percentual de contrapartida e prazos).

Regras seguidas (AGENTS.md):
- Preservar todas as linhas (nenhuma exclusao automatica).
- Datas placeholder/sentinela viram `NaT` e sao marcadas por flag, nunca apagadas do registro.
- Anos extraidos apenas de datas validas.
- Prazos calculados em dias, apenas entre datas validas.
- `valor_total_dolar` e `percentual_contrapartida` com tratamento explicito de nulo e divisao por zero.

---
---

## Tratar dt_ultimo_recebimento igual a 1940-01-01 como placeholder

A data `1940-01-01` aparece 382 vezes apenas em `dt_ultimo_recebimento`. Sem esse placeholder, a data minima real e 1989. Tratada como placeholder: vira `NaT` e e marcada por flag. O original ja foi preservado em `dt_ultimo_recebimento_original`.

In [101]:
PLACEHOLDER_RECEBIMENTO = pd.Timestamp("1940-01-01")

mask_placeholder = df_tratado["dt_ultimo_recebimento"] == PLACEHOLDER_RECEBIMENTO
df_tratado["flag_recebimento_placeholder"] = mask_placeholder

print("registros placeholder 1940-01-01:", mask_placeholder.sum())

df_tratado.loc[mask_placeholder, "dt_ultimo_recebimento"] = pd.NaT

print("min recebimento apos tratamento:", df_tratado["dt_ultimo_recebimento"].min())
print("max recebimento apos tratamento:", df_tratado["dt_ultimo_recebimento"].max())

registros placeholder 1940-01-01: 382
min recebimento apos tratamento: 1989-04-03 00:00:00
max recebimento apos tratamento: 2026-03-23 00:00:00

## Tratar datas extremas como sentinela (9999-12-31, 4201-01-01, 2225-01-01 e outras)

Datas claramente impossiveis (`9999-12-31`, `4201-01-01`, `2228-03-29`, `2225-01-01`, `2100-01-01`) sao sentinela/erro. Viram `NaT` e sao marcadas por `flag_data_sentinela`. Datas futuras plausiveis (ate 2052) sao mantidas, pois sao previsoes de desembolso aceitaveis.

In [102]:
DATAS_SENTINELA = [
    pd.Timestamp("9999-12-31"),
    pd.Timestamp("4201-01-01"),
    pd.Timestamp("2228-03-29"),
    pd.Timestamp("2225-01-01"),
    pd.Timestamp("2100-01-01"),
]

mask_sentinela = pd.Series(False, index=df_tratado.index)

for coluna in colunas_data:
    m = df_tratado[coluna].isin(DATAS_SENTINELA)
    if m.sum():
        print(f"{coluna}: {m.sum()} sentinela")
    mask_sentinela |= m
    df_tratado.loc[m, coluna] = pd.NaT

df_tratado["flag_data_sentinela"] = mask_sentinela
print("total registros com data sentinela:", mask_sentinela.sum())

dt_ultimo_desembolso_original: 4 sentinela
dt_ultimo_desembolso_vigente: 3 sentinela
total registros com data sentinela: 4

In [103]:
# Conferencia dos ranges apos tratamento de placeholder e sentinela
resumo_datas_transf = pd.DataFrame({
    "min": [df_tratado[c].min() for c in colunas_data],
    "max": [df_tratado[c].max() for c in colunas_data],
    "nulos": [df_tratado[c].isna().sum() for c in colunas_data],
}, index=colunas_data)

resumo_datas_transf

                                     min        max  nulos
dt_ultimo_recebimento         1989-04-03 2026-03-23    788
dt_primeira_cofiex            1990-05-30 2026-04-01   1630
dt_validade_recomendacao      2000-09-11 2027-12-22   2555
dt_reuniao_negociacao         1989-11-07 2026-04-01   2630
dt_publicacao_dou             1998-06-24 2025-11-21   2456
dt_assinatura                 1949-01-27 2025-12-30   2132
dt_ultimo_desembolso_original 1986-12-31 2034-02-28   2315
dt_ultimo_desembolso_vigente  1953-12-31 2052-02-20   2139

## Criar ano_recebimento

In [104]:
df_tratado["ano_recebimento"] = df_tratado["dt_ultimo_recebimento"].dt.year
print("nulos:", df_tratado["ano_recebimento"].isna().sum())
df_tratado["ano_recebimento"].value_counts(dropna=False).sort_index().tail(15)

nulos: 788

ano_recebimento
2013.0     63
2014.0     38
2015.0     30
2016.0     31
2017.0     86
2018.0     68
2019.0     71
2020.0     54
2021.0     64
2022.0     76
2023.0     84
2024.0    146
2025.0    105
2026.0      8
NaN       788
Name: count, dtype: int64

## Criar ano_primeira_cofiex

In [105]:
df_tratado["ano_primeira_cofiex"] = df_tratado["dt_primeira_cofiex"].dt.year
print("nulos:", df_tratado["ano_primeira_cofiex"].isna().sum())
df_tratado["ano_primeira_cofiex"].value_counts(dropna=False).sort_index().tail(15)

nulos: 1630

ano_primeira_cofiex
2013.0      34
2014.0      38
2015.0      19
2016.0      21
2017.0      38
2018.0      49
2019.0      43
2020.0      43
2021.0      40
2022.0      54
2023.0      74
2024.0      76
2025.0     106
2026.0       8
NaN       1630
Name: count, dtype: int64

## Criar ano_assinatura

In [106]:
df_tratado["ano_assinatura"] = df_tratado["dt_assinatura"].dt.year
print("nulos:", df_tratado["ano_assinatura"].isna().sum())
df_tratado["ano_assinatura"].value_counts(dropna=False).sort_index().tail(15)

nulos: 2132

ano_assinatura
2012.0      76
2013.0      49
2014.0      35
2015.0       6
2016.0      19
2017.0      27
2018.0      29
2019.0      34
2020.0      31
2021.0      19
2022.0      28
2023.0      33
2024.0      41
2025.0      18
NaN       2132
Name: count, dtype: int64

## Criar valor_total_dolar

`valor_total_dolar = vl_financiamento_dolar + vl_contrapartida_dolar`.

Regra de nulo (documentada): soma tratando ausente como 0, **mas** retorna `NaN` quando ambos sao nulos. Assim um registro sem nenhum valor financeiro nao vira 0 artificial.

In [107]:
fin = df_tratado["vl_financiamento_dolar"]
contra = df_tratado["vl_contrapartida_dolar"]

df_tratado["valor_total_dolar"] = fin.fillna(0) + contra.fillna(0)

ambos_nulos = fin.isna() & contra.isna()
df_tratado.loc[ambos_nulos, "valor_total_dolar"] = np.nan

print("ambos nulos (valor_total NaN):", ambos_nulos.sum())
print(df_tratado["valor_total_dolar"].describe())

ambos nulos (valor_total NaN): 245
count    3.303000e+03
mean     1.576658e+08
std      4.349027e+08
min      0.000000e+00
25%      1.000000e+07
50%      5.893100e+07
75%      1.500000e+08
max      1.021500e+10
Name: valor_total_dolar, dtype: float64

## Criar percentual_contrapartida

`percentual_contrapartida = vl_contrapartida_dolar / valor_total_dolar`.

Protecao contra divisao por zero e nulo: resultado fica `NaN` quando `valor_total_dolar` eh 0 ou nulo. Expresso em fracao (0 a 1).

In [108]:
total = df_tratado["valor_total_dolar"]

df_tratado["percentual_contrapartida"] = np.where(
    total.notna() & (total != 0),
    df_tratado["vl_contrapartida_dolar"].fillna(0) / total,
    np.nan,
)

print("nulos percentual:", df_tratado["percentual_contrapartida"].isna().sum())
print(df_tratado["percentual_contrapartida"].describe())

nulos percentual: 273
count    3275.000000
mean        0.254572
std         0.243891
min         0.000000
25%         0.000000
50%         0.200000
75%         0.433930
max         1.000000
Name: percentual_contrapartida, dtype: float64

## Criar prazo_recebimento_cofiex

Dias entre `dt_ultimo_recebimento` e `dt_primeira_cofiex`. Calculado apenas quando ambas as datas sao validas. Valor negativo indica inconsistencia cronologica (sera tratado por flag em validacao).

In [109]:
df_tratado["prazo_recebimento_cofiex"] = (
    df_tratado["dt_primeira_cofiex"] - df_tratado["dt_ultimo_recebimento"]
).dt.days

print("validos:", df_tratado["prazo_recebimento_cofiex"].notna().sum())
print("negativos:", (df_tratado["prazo_recebimento_cofiex"] < 0).sum())
print(df_tratado["prazo_recebimento_cofiex"].describe())

validos: 1805
negativos: 75
count    1805.000000
mean      196.494183
std       534.327591
min     -5300.000000
25%        36.000000
50%        77.000000
75%       220.000000
max      3812.000000
Name: prazo_recebimento_cofiex, dtype: float64

## Criar prazo_cofiex_assinatura

Dias entre `dt_primeira_cofiex` e `dt_assinatura`. Apenas datas validas.

In [110]:
df_tratado["prazo_cofiex_assinatura"] = (
    df_tratado["dt_assinatura"] - df_tratado["dt_primeira_cofiex"]
).dt.days

print("validos:", df_tratado["prazo_cofiex_assinatura"].notna().sum())
print("negativos:", (df_tratado["prazo_cofiex_assinatura"] < 0).sum())
print(df_tratado["prazo_cofiex_assinatura"].describe())

validos: 1048
negativos: 37
count    1048.000000
mean      726.285305
std       731.383542
min     -6011.000000
25%       298.750000
50%       623.500000
75%      1015.750000
max      5671.000000
Name: prazo_cofiex_assinatura, dtype: float64

## Criar prazo_assinatura_desembolso

Dias entre `dt_assinatura` e `dt_ultimo_desembolso_vigente`. Apenas datas validas.

In [111]:
df_tratado["prazo_assinatura_desembolso"] = (
    df_tratado["dt_ultimo_desembolso_vigente"] - df_tratado["dt_assinatura"]
).dt.days

print("validos:", df_tratado["prazo_assinatura_desembolso"].notna().sum())
print("negativos:", (df_tratado["prazo_assinatura_desembolso"] < 0).sum())
print(df_tratado["prazo_assinatura_desembolso"].describe())

validos: 1364
negativos: 1
count    1364.000000
mean     2062.362903
std      1058.201476
min      -192.000000
25%      1440.500000
50%      2031.000000
75%      2664.000000
max      7304.000000
Name: prazo_assinatura_desembolso, dtype: float64

## Validacao final da transformacao

In [112]:
assert len(df_tratado) == len(df_raw), "Quantidade de linhas mudou!"

derivadas = [
    "ano_recebimento", "ano_primeira_cofiex", "ano_assinatura",
    "valor_total_dolar", "percentual_contrapartida",
    "prazo_recebimento_cofiex", "prazo_cofiex_assinatura", "prazo_assinatura_desembolso",
]

print("linhas:", len(df_tratado))
print("colunas no df_tratado:", df_tratado.shape[1])
print("derivadas presentes:", all(c in df_tratado.columns for c in derivadas))
print("flag_recebimento_placeholder:", df_tratado["flag_recebimento_placeholder"].sum())
print("flag_data_sentinela:", df_tratado["flag_data_sentinela"].sum())

linhas: 3548
colunas no df_tratado: 60
derivadas presentes: True
flag_recebimento_placeholder: 382
flag_data_sentinela: 4

---

## Carga: salvar base tratada

Exporta o `df_tratado` para `dados_tratados/cofiex_tratado.csv` em `utf-8-sig`. A base bruta em `dados_brutos/` permanece intacta. Ao final, testa a releitura do CSV.

In [113]:
DIR_TRATADOS = BASE_DIR / "dados_tratados"
DIR_TRATADOS.mkdir(exist_ok=True)

CAMINHO_TRATADO = DIR_TRATADOS / "cofiex_tratado.csv"

df_tratado.to_csv(CAMINHO_TRATADO, index=False, encoding="utf-8-sig")
print("salvo em:", CAMINHO_TRATADO)
print("shape exportado:", df_tratado.shape)

salvo em: C:\Users\heron\Downloads\CofiexBI\dados_tratados\cofiex_tratado.csv
shape exportado: (3548, 60)

In [114]:
# Teste de releitura do CSV exportado
df_teste = pd.read_csv(CAMINHO_TRATADO, encoding="utf-8-sig")

print("linhas relidas:", len(df_teste))
print("colunas relidas:", df_teste.shape[1])
assert len(df_teste) == len(df_tratado), "Linhas divergem apos releitura!"
print("LEITURA OK")

linhas relidas: 3548
colunas relidas: 60
LEITURA OK